### ISSUE TITLE
Query filter on __key__ using the "IN" operator

### ISSUE THREAD

**Issue by Guillaume-Sensome** [googleapis/nodejs-datastore#1024]
#### Context

The datastore API allows filtering on `__key__` with the "IN" operator and an array of Keys as value.  
I want to do using this library.

#### Problem description

This lib does not allow to query entities filtering on __key__ using the "IN" operator, and throws:  
`InvalidKey: A key should contain at least a kind.`  
=> The code expects a Key when I send an array of Keys.

#### Steps to reproduce

```js
const entitiesKey = [
  datastore.key({
    namespace,
    path: [kind, '01ece338-066d-443b-8c33-15414f971092']
  }),
  datastore.key({
    namespace,
    path: [kind, '0750f7ed-caf5-44d4-9105-0d72a81eeb9b']
  })
]
const query = datastore.createQuery(namespace, kind)
query.filter('__key__', 'IN', entitiesKey)
const entities = datastore.runQuery(query)
```

Throwing this:
```log
InvalidKey: A key should contain at least a kind.
    at Object.keyToKeyProto (C:\www\senfab\node_modules\@google-cloud\datastore\build\src\entity.js:974:19)
    at C:\www\senfab\node_modules\@google-cloud\datastore\build\src\entity.js:1108:45
    at Array.map (<anonymous>)
    at Object.queryToQueryProto (C:\www\senfab\node_modules\@google-cloud\datastore\build\src\entity.js:1104:43)
    at makeRequest (C:\www\senfab\node_modules\@google-cloud\datastore\build\src\request.js:273:49)
```

#### Results explanation

=> In build/src/entity.js l.1107, in the queryToQueryProto function, these lines are causing me trouble:
````js
if (filter.name === '__key__') {
    value.keyValue = entity.keyToKeyProto(filter.val);
}
else {
    value = entity.encodeValue(filter.val, filter.name);
}
````
=> `entity.encodeValue` handle correctly if `filter.val` is an array, but `entity.keyToKeyProto` doesn't handle arrays,  
whereas the API does handle filtering on `__key__` with the "IN" operator and an array as value.

#### Code suggestion

Patching this code is enough to make it work:
```js
if (filter.name === '__key__') {
  if (Array.isArray(filter.val)) {
    value = {
      arrayValue: {
        values: filter.val.map(v => {
          return {
            keyValue: entity.keyToKeyProto(v)
          }
        })
      }
    }
  } else {
    value.keyValue = entity.keyToKeyProto(filter.val)
  }
} else {
  value = entity.encodeValue(filter.val, filter.name)
}
```

#### Environment details

  - OS: Windows 10
  - Node.js version: 16.14.0
  - npm version: 8.3.1
  - `@google-cloud/datastore` version: 7.0.0

**Comment by vicb** [comment]
I think the way to do this is

await datastore.get(entityKeys);

**Comment by Guillaume-Sensome** [comment]
> I think the way to do this is
> 
> await datastore.get(entityKeys);

Indeed, in the example I gave, it is better to use `datastore.get(entityKeys);`.

My need is more complex, and I'm applying a `select` and one more `filter`.  
Something like:
```js
const entitiesKey = [
  datastore.key({
    namespace,
    path: [kind, '01ece338-066d-443b-8c33-15414f971092']
  }),
  datastore.key({
    namespace,
    path: [kind, '0750f7ed-caf5-44d4-9105-0d72a81eeb9b']
  })
]
const query = datastore.createQuery(namespace, kind)
query.filter('parameters.availability', '=', true)
query.filter('__key__', 'IN', entitiesKey)
query.select('parameters.serial_number')
const entities = datastore.runQuery(query)
```

**Comment by vicb** [comment]
Makes sense.

Looking at the code is seems that the fix might be to not special case `__key__` at https://github.com/googleapis/nodejs-datastore/blob/465c6cadee9f534b4c29e746674535f00f586390/src/entity.ts#L1260-L1264

Replacing that code with only

```
value = entity.encodeValue(filter.val, filter.name);
```

As `encodeValue` can encode:
- An array of values at https://github.com/googleapis/nodejs-datastore/blob/465c6cadee9f534b4c29e746674535f00f586390/src/entity.ts#L667-L672
- Keys at https://github.com/googleapis/nodejs-datastore/blob/465c6cadee9f534b4c29e746674535f00f586390/src/entity.ts#L674-L677

**Comment by Guillaume-Sensome** [comment]
Thank you @vicb!  
You're right, the patch should be to ignore the special case `if (filter.name === '__key__')`.

Replace that code:
https://github.com/googleapis/nodejs-datastore/blob/465c6cadee9f534b4c29e746674535f00f586390/src/entity.ts#L1256-L1264

...with only:

```js
        const filters = query.filters.map(filter => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        let value: any = entity.encodeValue(filter.val, filter.name);
```

Should I do a PR of that?

**Comment by vicb** [comment]
```
let value: any = entity.encodeValue(filter.val, filter.name);
```

You do not need to specify the type (`:any`) here at it will be inferred from `encodeValue` (as `ValueProto`). But you can probably inline `value` as it is used only in one place (or at least make it a `const`).

If you create a PR with the code change and a test for `Array<Keys>` it would probably help get it merged faster.

**Comment by danieljbruce** [comment]
We don't want to ignore the check for `if (filter.name === '__key__') {` because this will not enable us to encode requests where we want to search by `__key__` and we don't use an array.

**Comment by danieljbruce** [comment]
I guess if the alternate code path still encodes the values correctly though then this could work.

**Comment by danieljbruce** [comment]
Seems to here:

https://github.com/googleapis/nodejs-datastore/blob/3a76e15d7d3fc066cca8fd51d39f5ccf3b958528/src/entity.ts#L674

As long as the value is guaranteed to be a key. But what if it isn't?

**Comment by vicb** [comment]
Hey @danieljbruce not sure who you are asking the question to?

> As long as the value is guaranteed to be a key. But what if it isn't?

What's the problem here?

if you `query.filter('numberField',  "some string")` it would just returns nothing. Why should the `__key__` be any different?

(I hope I am not saying a stupid thing here - hard to context switch while I'm in a middle of other stuff)

**Comment by danieljbruce** [comment]
I think we are good here because the compiler guarantees the type `Key` in `keyToKeyProto(key: Key)` so we should be good to move on and accept the changes. Just leaving notes here as I investigate the code.

**Comment by danieljbruce** [comment]
@vicb 

So the code in the PR has been refactored out into a `PropertyFilter` method since the original PR was posted.

What you will notice is that we can't make the corresponding change in the new code because it will actually cause some tests to fail.

https://github.com/googleapis/nodejs-datastore/pull/1079/files

**Comment by danieljbruce** [comment]
@vicb As discussed, we can avoid having to change the datastore key check by using another import entirely in the tests: 

https://github.com/googleapis/nodejs-datastore/pull/1083
