### ISSUE TITLE
How to generate URL-safe key?

### ISSUE THREAD

**Issue by bretthadley** [googleapis/nodejs-datastore#105]
Hi, I can't find it in the documentation on how to generate a url-safe key?

Thanks

**Comment by stephenplusplus** [comment]
Regarding the URL safe part, you can run any value through `encodeURIComponent`. I probably shouldn't comment on any best practices about generating the key-- @JustinBeckwith, should we ask someone from Datastore?

**Comment by bretthadley** [comment]
Hi @stephenplusplus / @JustinBeckwith 

I need to generate the URL-safe key we see inside the datastore UI.

Regards, Brett.

**Comment by callmehiphop** [comment]
@bretthadley sorry for the blast from the past, but did you ever figure out the answer to this?

**Comment by jiren** [comment]
To generate URL - safe key required app engine protobuf Key structure (which include Reference and Path element). I am checking in detail how we can generate it.

**Comment by AVaksman** [comment]
Closed with #456
