### ISSUE TITLE
Plase support Aggregation queries

### ISSUE THREAD

**Issue by MiguiTE** [googleapis/nodejs-datastore#1060]
Recently Datastore has been update to perform aggregation queries (at least, a `count` query). According to the [documentation](https://cloud.google.com/datastore/docs/aggregation-queries), there is an preview implementation in Java. It will be nice if the nodejs client also supports these aggregation queries.

Thanks.

**Comment by vicb** [comment]
That would be very nice indeed.

The thing is it seems like it's already implemented in https://github.com/googleapis/nodejs-datastore/commit/d5c2cb1f0725f3cce1dde5b80ac7aff55b605f9a and it only needs to be released.

I'm not exactly sure as I also see https://github.com/googleapis/nodejs-datastore/pull/972.

**Comment by vicb** [comment]
@danieljbruce Do you have any ETA for the next release ? Thanks

**Comment by kolea2** [comment]
This has just been released: https://github.com/googleapis/nodejs-datastore/releases/tag/v7.1.0. Please let us know if you run into any issues!

**Comment by vicb** [comment]
I'm using count queries and it works well. Thanks.
