### ISSUE TITLE
In the new AppEngine Node.js Standard "resumable: false" is needed

### ISSUE THREAD

**Issue by juliantoledo** [googleapis/nodejs-datastore#108]
I just migrated my flex project to AppEngine Node.js Standard and found that "resumable: false" is needed because gcs-resumable-upload tries to write to disk if resumable is enable (this is not allowed in the Standard version)

#### Steps to reproduce

  1. Upload an image similarly to https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/8bb3d70596cb0c1851cd587d393faa76bfad8f80/3-binary-data/lib/images.js
  2. with resumable: enable

Thank you

**Comment by JustinBeckwith** [comment]
This issue was moved to googleapis/nodejs-storage#232
