### ISSUE TITLE
Typescript + query + filter: export `PropertyFilter` with the main library and incorrect docs

### ISSUE THREAD

**Issue by jarrodek** [googleapis/nodejs-datastore#1086]
Thanks for stopping by to let us know something could be better!

1) Is this a client library issue or a product issue?
This is an issue with the library.

2) Did someone already solve this?
I searched for issues and SO for relevant question. Couldn't find anything about it.

3) Do you have a support contract?
Nope :(

#### Environment details

  - OS: Ubuntu 22.04.2 LTS 
  - Node.js version: v18.15.0
  - npm version: 9.5.0
  - `@google-cloud/datastore` version: 7.4.0

#### Explainer

When making a query I am getting the following warning messages in the terminal:
```sh
(node:25821) Warning: Providing Filter objects like Composite Filter or Property Filter is recommended when using .filter
```
I was surprised at first because I was following the documentation to create a query. The original one was something to the effect of:

```typescript
const query = store.createQuery('MyKind')
      .filter('a', '=', 'b')
      .filter('c', '=', 'd');
```
Giving the warning message I dag deeper into TS declarations to find `PropertyFilter` class declaration in `@google-cloud/datastore/build/src/filter.d.ts`. As a result I changed my query to something to the effect of:

```typescript
import { Datastore } from '@google-cloud/datastore';
import { PropertyFilter } from '@google-cloud/datastore/build/src/filter.js';

const query = store.createQuery('MyKind')
      .filter(new PropertyFilter('a', '=', 'b'))
      .filter(new PropertyFilter('c', '=', 'd'));
```

The warning message is not printed in the terminal anymore.

Two things here which can be improved:

1. The documentation probably should mention anything about that. I only figured it out because I looked into the source files.
2. The `PropertyFilter` is not exported through the "main" file (not in the types declaration file at least). Because of that I have to import the `PropertyFilter` directly from the source file which I don't consider safe behavior as any change in the library structure could potentially break my code.

Hope this helps. Cheers!

P.S.
The `CompositeFilter` class is not event exported. The warning message suggested to use property of composite filters.

**Comment by danieljbruce** [comment]
It is now supported as shown by the following line of code:

https://github.com/googleapis/nodejs-datastore/blob/dd2d5f4d15f714b3f3586250802fb6822b7e01ff/src/index.ts#L46

With the following change:

https://github.com/googleapis/nodejs-datastore/pull/1092/files

If you want to use a composite filter then use `and` or `or` as these are now exported from the main file and so will be available in the next release.
