### ISSUE TITLE
Getting a faster count of total entities

### ISSUE THREAD

**Issue by mcfarljw** [googleapis/nodejs-datastore#109]
We have some account downloads which are a bit larger and it would be great to be able to easily give users some kind of progress indication. Is there a quick and easy way to get a simple count on an indexed property?

I have tried doing `query.select('__key__')`, but it's still a bit slow for getting a count of 10,000+ entities.

I found a question about it in general here (https://groups.google.com/forum/#!topic/gcd-discuss/wH8lVOA-a8Y), but it kind of seems like client libraries don't support this or at least I can't find it in the documentation.

_This is more of a question than bug report so I've only included the version of datastore we're currently using._

#### Environment details

  - `@google-cloud/datastore` version: 1.4.x

**Comment by beaulac** [comment]
As far as I can tell, the `skipped_results` property is not currently present in the API response available to the nodeJS client, so this workaround is not usable without some modification of the client 😢 

If you're trying to push performance on large datasets right now, I think sharding would be a better investment than trying this API-optimization recipe anyway.

**Comment by davalapar** [comment]
Hi mcfarljw,

Iterating on each entities in the tables for the headcount could be really expensive in terms of time.

I think a better approach is to do a headcount once (or start from zero if its a determinate progress), cache this result/value in some reliable session storage then just increment / decrement it every time there's a successful commit or removal of an entity entry.

**Comment by callmehiphop** [comment]
As @beaulac pointed out `skippedResults` is currently not available via the hand written client. However you should be able to get this info by using the generated `DatastoreClient`.

```js
const datastore = require('@google-cloud/datastore');
const client = new datastore.v1.DatastoreClient();

const query = {
  projectId: process.env.GCLOUD_PROJECT,
  gqlQuery: {
    queryString: 'SELECT * FROM MyKind LIMIT @limit OFFSET @offset',
    namedBindings: {
      limit: {
        value: {
          integerValue: 0
        },
      },
      offset: {
        value: {
          integerValue: 100
        },
      }
    }
  }
};

const [queryResponse] = await client.runQuery(query);
const {skippedResults} = queryResponse.batch;
```
