### ISSUE TITLE
datastore: document unit testing with the emulator

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-datastore#11]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2441

<a href="/jgeewax"><img src="https://avatars2.githubusercontent.com/u/112928?s=88&v=4" height=44 width=44 align=left></a><a href="/jgeewax">@&shy;jgeewax</a><br>July 7, 2017 11:52 AM

After ... far too long trying to figure out how to do testing, I stumbled upon `google-datastore-emulator`, which makes life way easier.

Can we document that a nice test runner if you use datastore would look something like...

```js
const spawn = require('child_process').spawn;
const DatastoreEmulator = require('google-datastore-emulator');

// Create a datastore emulator.
const datastoreEmulator = new DatastoreEmulator({
  projectId: 'projectId',
  storeOnDisk: false,
  clean: true,
});

// Args passed to this runner should be forwarded to mocha.
// Things can be run as node script.js --args or just nodescript --args
let args = process.argv;
if (args[0] == process.execPath) {
  args = args.slice(1);
}
args = args.slice(1);

// Start the emulator.
datastoreEmulator.start().then(() => {
  // Run mocha as a child process.
  const mochaProcess = spawn('mocha', args, { stdio: 'inherit' });
  // When the process exits, stop the emulator, and exit with the same exit code.
  mochaProcess.on('exit', (code, signal) => {
    datastoreEmulator.stop().then(() => {
      process.exit(code);
    });
  });
});
```

**Comment by stephenplusplus** [comment]
<a href="/lukesneeringer"><img src="https://avatars2.githubusercontent.com/u/4346?s=88&v=4" height=44 width=44 align=left></a>__<a href="/lukesneeringer">@&shy;lukesneeringer</a>__<br>July 10, 2017 2:58 PM

@stephenplusplus This seems reasonable. How long would it take to add a page like this?

**Comment by stephenplusplus** [comment]
<a href="/jgeewax"><img src="https://avatars2.githubusercontent.com/u/112928?s=88&v=4" height=44 width=44 align=left></a>__<a href="/jgeewax">@&shy;jgeewax</a>__<br>July 11, 2017 8:52 PM

We should also note that you need to install the Cloud SDK, and the beta commands, and the datastore emulator :)

**Comment by stephenplusplus** [comment]
<a href="/callmehiphop"><img src="https://avatars2.githubusercontent.com/u/1707267?s=88&v=4" height=44 width=44 align=left></a>__<a href="/callmehiphop">@&shy;callmehiphop</a>__<br>July 12, 2017 11:17 AM

Where would something like this live on the site? My initial thought would be to add some kind of guide to the `Getting Started` section that gives a general overview of unit testing for any module with a list of emulator modules (where applicable) per API?

**Comment by stephenplusplus** [comment]
<a href="/lukesneeringer"><img src="https://avatars2.githubusercontent.com/u/4346?s=88&v=4" height=44 width=44 align=left></a>__<a href="/lukesneeringer">@&shy;lukesneeringer</a>__<br>July 12, 2017 7:20 PM

I would be fine with that. I would probably be okay making this something that happens after the reorg; we could do Datastore early. (Even first.)

**Comment by callmehiphop** [comment]
I think now that our old doc site is dead, the proposed solution is no longer possible.

/cc @jmdobry @alexander-fenster

**Comment by kirillgroshkov** [comment]
Yes, would be really nice!

**Comment by callmehiphop** [comment]
@stephenplusplus if we had guides, it would be easy enough to give a shout out to the gcloud tool emulators in addition to a quick recipe for specifying the `servicePath` and `port` options.

**Comment by stephenplusplus** [comment]
Did we lose the docs that showed how to use the emulator? I believe it was attached to the constructor.

**Comment by callmehiphop** [comment]
Actually they are still there in Datastore ([link](https://googleapis.dev/nodejs/datastore/latest/Datastore.html)), however it is worth noting that the landing page is now the README and users would need to navigate to the `Datastore` constructor page which might not be super intuitive.

**Comment by stephenplusplus** [comment]
I think we're doing okay for showing how to use the emulator, and if we want to go bigger with the guides concept, after adding support, we would be able to choose all of the topics that should be highlighted, of which this would be only one. Please re-open if this was a bad move and there's more that should be done now.

**Comment by mbyrne00** [comment]
Hi - firstly thanks for the great work with this lib.

I'm a bit confused as to the resolution here. I can only see docs showing how to use emulator from command line and no test examples. I think if code samples are shown it would be really useful to show a code sample with a test that hits the database (via emulator). This is one of the biggest areas of confusion between the node stack and the great testing tools offered in a stack like the Java one. Each codebase I see on this stack is over-using mocks/spy and the tests are more complex as a result ... would love to get a clean example hitting the database (and from what I've seen it's confused other people too).

**Comment by stephenplusplus** [comment]
Hey @mbyrne00, thanks for the support. It's true, it looks like we don't have sample code for using the emulator. After the emulator is running, if you set the environment variable that the emulator prepares, our library should pick it up and send all Datastore API calls to it. In other words, it should actually be code-less, just a matter of the env var.

To be explicit, you can set the `apiEndpoint` option when you create the Datastore class:

```ts
const ds = new Datastore({ apiEndpoint: 'localhost:8005' })
ds.query().run() // goes to emulator
```

> I see on this stack is over-using mocks/spy and the tests are more complex as a result

Those are our unit tests using all of the mocks. You could check out the system tests file, which hits the real API: https://github.com/googleapis/nodejs-datastore/blob/master/system-test/datastore.ts (no emulator tests there, however)

**Comment by mbyrne00** [comment]
Hey @stephenplusplus - thanks for the info. My reference to unit tests using too many mocks was more in application codebases I've seen.

It's great that the tests can connect to an emulator that has been started externally, but the java appengine testing lib allows for "Local services" to be started and stopped with every test and one example is DataStore which does not slow things down noticeably. 

We use jest, but I was really interested to see the example in the body by @­jgeewax which seems closer to what we've used before and wondering if there were any examples using this approach? This way the caller of a test does not need to setup anything externally.

**Comment by stephenplusplus** [comment]
Thanks for the added detail. I'm willing to admit I could be overthinking all of this, and we should just throw caution to the wind and write examples, so let me know your opinions.

As far as I know, we haven't looked into creating our own emulator controller. Short of that, I don't believe we should document using a third party library for reasons I mentioned earlier in the thread about it going stale, and it somewhat gives it a stamp of approval, when I'm not sure we know enough about it.

It would make sense to me to encourage/contribute sufficient examples on the google-datastore-emulator repo. If we think the library is stable-ish enough, where we reference connecting with the emulator in our docs, we can include a link to their page.

@JustinBeckwith whatcha think?

**Comment by JustinBeckwith** [comment]
@stephenplusplus everything you said sounds right to me.  

I suspect Java is able to get the quality of testing library you're seeing because I believe the Datastore emulator in the Cloud SDK is actually _written_ in Java - so it's even possible they're doing all of that stuff in process.

**Comment by meredithslota** [comment]
Just closing out this conversation with a summary of changes since the last comment. :) 

The documentation for the Datastore emulator lives here: https://cloud.google.com/datastore/docs/tools/datastore-emulator (it's a language-agnostic page). The `gcloud` Datastore emulator reference has a handful of code samples. Additionally, we've migrated client library code samples into this repo where they are now tested alongside the library; you can review our tests here: https://github.com/googleapis/nodejs-datastore/tree/main/samples/test

 If there are specific samples that are missing that could be helpful, please file a new issue. Thanks!

**Comment by antonytrupe** [comment]
The example tests will connect to the cloud datastore by default, right? You'd have to manually start the emulator. How do you start the emulator automagically when the tests are run?
