### ISSUE TITLE
Do not clutter the logs with warnings in prod environment

### ISSUE THREAD

**Issue by vicb** [googleapis/nodejs-datastore#1109]
The [following code](https://github.com/googleapis/nodejs-datastore/blob/cd59c718ebe6711603b08b3ba2677e5a984bc7e3/src/query.ts#LL198C1-L200C34)

```js
 const companyQuery = query
   .filter('name', 'Google')
   .filter('size', '<', 400);
```

will print a warning:

```js
process.emitWarning(
  'Providing Filter objects like Composite Filter or Property Filter is recommended when using .filter'
);
```

First I don't think there should be any warning in a prod environment.
One way js libraries check for prod environemnt is to check if the `NODE_ENV` environment variable is set to `production` - see the [express docs](https://expressjs.com/en/advanced/best-practice-performance.html#set-node_env-to-production) for ref.

Also my understanding is that the warning is there because of nested composite filters. I don't think there should be any warnings in a simple case, that is:

```js
const companyQuery = query.filter('name', 'Google');
```

should probably not generate a warning even in dev env.

/cc @danieljbruce

**Comment by danieljbruce** [comment]
[Datastore in Python](https://github.com/googleapis/python-datastore/blob/b31a94455365445f5abc4eefc5edbef275ecc750/google/cloud/datastore/query.py#L432) emits this warning too so whatever we end up doing there should probably be consistency across the board.

**Comment by vicb** [comment]
I am not familiar with Python `warnings` but it looks like you can at least [filter the warnings](https://docs.python.org/3/library/warnings.html#the-warnings-filter)

**Comment by vicb** [comment]
This is what I mean:

<img width="1122" alt="image" src="https://github.com/googleapis/nodejs-datastore/assets/248818/f64a6440-93f8-4e3f-9acf-25a5efca242f">

It would be great to filter out all the noise in my prod env.

Thanks!

**Comment by MiguiTE** [comment]
What should be done not to get this warning when building a query with filters?

According to docs there are two ways of filtering a query, [with](https://cloud.google.com/nodejs/docs/reference/datastore/latest/datastore/query#_google_cloud_datastore_Query_filter_member_2_) operator and [without](https://cloud.google.com/nodejs/docs/reference/datastore/latest/datastore/query#_google_cloud_datastore_Query_filter_member_1_) (defaults to equals). So, how could we build and supply a _Filter object_?

**Comment by vicb** [comment]
It looks like the doc is not up to date. The filter method can now take objects. You can look at the tests for an example.

That being said I think using the legacy way (with and without operator) should still be supported and should not log a warning at least in production mode.

**Comment by efossvold** [comment]
Using PropertyFilter eliminates the warning.

```
import { Datastore, PropertyFilter } from '@google-cloud/datastore'
const ds = new Datastore()
const query = ds.createQuery('Kind')
.filter(new PropertyFilter('foo', '=', 'bar'))
.filter(new PropertyFilter('baz', '=', 'quux'))
```

**Comment by vicb** [comment]
@efossvold read my initial message. I said I don't think we should be forced to do that for simple case because there is no point. Thanks for trying to help though.
