### ISSUE TITLE
Ability to specify which Firestore database to use

### ISSUE THREAD

**Issue by udnes99** [googleapis/nodejs-datastore#1130]
On July 7th, Google released a [new feature](https://cloud.google.com/blog/products/databases/manage-multiple-firestore-databases-in-a-project) allowing multiple Firestore databases to be created within a GCP project.
This makes it possible to have separate environments that can be used for development, without having to rely on the outdated and buggy emulator. However, this SDK needs to be updated to support this new feature. Is this something that is planned for release?

**Comment by FredrikAugust** [comment]
This is currently a highly desired feature for us as we'd like to use the new multiple database functionality!

**Comment by danieljbruce** [comment]
https://github.com/googleapis/nodejs-datastore/pull/1090 will add such a feature

**Comment by danieljbruce** [comment]
This feature has been released.
