### ISSUE TITLE
Datastore Key Symbol not working

### ISSUE THREAD

**Issue by aaronclong** [googleapis/nodejs-datastore#1193]
The static property for `KEY` on Datastore doesn't work for retrieving the entity key from the entity.

A work around is to use `Object.getOwnPropertySymbols` and search the description to find the hidden Key object. Is there a way to fix this or provide a helper for easier Key access from the returned entity?

Unfortunately, I can't share more than this screenshot below: 

![StaticKeyPropertyNotWorking](https://github.com/googleapis/nodejs-datastore/assets/7354981/7b70b209-e01c-4872-af3a-27209e359cf9)

#### Environment details

  - OS: macOS, linux
  - Node.js version: 18
  - yarn v1
  - `@google-cloud/datastore` version: 8.0.0

**Comment by danieljbruce** [comment]
Could you provide a code sample that reproduces the problem please?

The code sample below seems to work just fine. Please reopen if this is still a problem.

```
const {Datastore} = require('@google-cloud/datastore');
const datastore = new Datastore();

async function printResults() {
  const kind = "key";
  const taskKey = datastore.key([kind, 1]);
  const newTask = {
    key: taskKey,
    data: {
      value: 999,
    },
  };
  await datastore.save(newTask, {});
  const [entity] = await datastore.get(taskKey);
  const returnedKey = entity[Datastore.KEY];
  console.log(returnedKey);
}

printResults();
```
