### ISSUE TITLE
Inconsistent processing of large numbers from other languages.

### ISSUE THREAD

**Issue by huysamen** [googleapis/nodejs-datastore#147]
Because javascript cannot process large numbers, it becomes extremely difficult to work with integrated systems.

We have Java applications storing large `long` values to Datastore, which now has a type `Integer` in Datastore.  These are then unable to be read by systems using node.

While the node version can also STORE large values by using the `datastore.int()` method, when reading the value out of the database, it is automatically read as a `number` javascript type, and therefore truncated.

**Comment by stephenplusplus** [comment]
True, we currently return raw Number values for integer and double values. (Lines for reference: https://github.com/googleapis/nodejs-datastore/blob/357839b76f8c8b5e87cd44b350fefbc2d6c9d138/src/entity.js#L270-L276)

We should probably return our custom types, `Int` and `Double`. The downside is that the majority of the time, the user will want the parsed Number, as their values aren't out of bounds. However, we don't have any support for when a value *is* out of bounds, which isn't too good.

@JustinBeckwith any thoughts on if we should make this breaking change? I believe breaking changes don't scare us anymore?

**Comment by huysamen** [comment]
Yeah I have already published a npm package just for us that uses the ‘long’ npm library, but using the Datastore “native” Int and Double objects would be preferable, if they support math operators (which I dont think they do). Otherwise I would say go with ‘long’ for Int and maybe ‘big-decimal’ or something for Double.

But from our side, break away with the changes! Claim it in the name of progress ;)

**Comment by callmehiphop** [comment]
I kind of think we should take a similar approach to whats being suggested in https://github.com/googleapis/nodejs-bigquery/issues/6, essentially allowing a user to specify custom types to cast to. This has the added benefit of not being breaking.

@stephenplusplus @bcoe @JustinBeckwith thoughts?

**Comment by bcoe** [comment]
@callmehiphop I very much like the idea of a consistent approach between the two libraries :+1:

**Comment by JustinBeckwith** [comment]
@callmehiphop could I ask you take this one on?
