### ISSUE TITLE
Getting error TypeError: Cannot read property 'createInsecure' of undefined

### ISSUE THREAD

**Issue by tahomatx** [googleapis/nodejs-datastore#15]
Hi,
Thank you for develop this library.

I got a error using datastore, so I wanna help.

#### Environment details

  - OS: Docker on Windows 10 (library/node docker image, not slim or alpine but standard)
  - Node.js version: 9.2.0
  - npm version: 5.5.1 (I'm using yarn 1.3.2)
  - @google-cloud/datastore version: 1.2.0

#### Steps to reproduce

  1. Set environment variable `DATASTORE_EMULATOR_HOST=datastore:8081` to use emulator
  2. In my code, `require('@google-cloud/datastore')();`

I got error:

```
/node_modules/@google-cloud/datastore/src/index.js:400
    this.options.sslCreds = grpc.credentials.createInsecure();
                                             ^

TypeError: Cannot read property 'createInsecure' of undefined
    at new Datastore (/node_modules/@google-cloud/datastore/src/index.js:400:46)
    at Datastore (/node_modules/@google-cloud/datastore/src/index.js:366:12)
    at Object.<anonymous> (/app/test.js:3:35)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
```

I think this stackoverflow question is the same issue.
<https://stackoverflow.com/questions/47860766/google-cloud-datastore-cannot-read-property-createinsecure-of-undefined>

Thanks for any help!

**Comment by callmehiphop** [comment]
@stephenplusplus I think [this line](https://github.com/googleapis/nodejs-datastore/blob/master/src/index.js#L22) is getting us in trouble here. I believe this returns a grpc wrapper and not an actual grpc instance. I think we can do this however

```js
var grpc = require('google-gax').grpc().grpc;
```

WDYT?

**Comment by stephenplusplus** [comment]
Ah, that's likely the problem then.

**Comment by tahomatx** [comment]
Thank you so much!!!!
ありがとう(^o^)
