### ISSUE TITLE
How to query an embedded entity (array of objects)?

### ISSUE THREAD

**Issue by charnould** [googleapis/nodejs-datastore#156]
Hi, 

I do not know if it's the right place to post such a question, but I've searched GitHub issues and asked for some clue on SO without success.

#### Environment details

  - OS: Mac os High Sierra
  - Node.js version: 8.x.x
  - npm version: 6.2.0
  - `@google-cloud/datastore` version: 1.4.1

#### Steps to reproduce

  1. Consider an `entity` containing the following `embedded entity`

```
{
  "values": [
    {
      "entityValue": {
        "properties": {
          "ACTION": {
            "stringValue": "proposal_created"
          },
          "TIMESTAMP": {
            "stringValue": "2018-08-02T11:42:00.000Z"
          }
        }
      }
    },
    {
      "entityValue": {
        "properties": {
          "TIMESTAMP": {
            "stringValue": "2018-08-02T11:42:12.000Z"
          },
          "ACTION": {
            "stringValue": "proposal_delivered"
          }
        }
      }
    },
    {
      "entityValue": {
        "properties": {
          "ACTION": {
            "stringValue": "proposal_expired"
          },
          "TIMESTAMP": {
            "stringValue": "2018-08-08T21:59:59.999Z"
          }
        }
      }
    }
  ]
}
```

  2. I am perfectly able to query this `embedded entity` by `TIMELINE.ACTION` or `TIMELINE.TIMESTAMP` (even if `TIMESTAMP` is stored as a `string` and not as a `date`...).

  3. However I'm totally unable to write a query of this kind:
Query all entities where `ACTION` = `'proposal_expired'` **and for which** `TIMESTAMP` < `new Date()` ?

  4. I heard about `composite index` (I do not know how if it's the road to walk), but I do not have any idea how to write such a query for Datastore, or even if that's possible.

Do you have any clue?
Documentation isn't helpful on this subject.
Thanks.

**Comment by davalapar** [comment]
Not sure if this fits well for your implementation, but in our (somewhat similar) case what we did is put those embedded values in a separate table with their own keys, then use their key names (or id's) as the value to that row.

On the top of my head here's an example:

#### Orders

| name/id | item | amount | payoutGroup |
| --- | --- | --- | --- |
| x1 | burger | 100 | z1 |
| x2 | fries | 200 | z1 |
| x3 | shake | 300 | z1 |


#### Payouts

| name/id | dateStart | dateEnd | paid | involvedOrders |
| --- | --- | --- | --- | --- |
| z1 | january1 | january31 | false | [x1, x2, x3] |

In which case, I could filter the Orders by payoutGroup and other row values, and at the same time filter Payouts by involvedOrders by their involved / included orders alone.

**Comment by stephenplusplus** [comment]
Sorry for the delay, @charnould. This question doesn't appear specific to our library or Node, so would you mind opening an issue on StackOverflow?: https://stackoverflow.com/questions/tagged/google-cloud-datastore.

**Comment by stephenplusplus** [comment]
If you still can't get a good answer, please let me know and I can escalate as necessary. Thanks!
