### ISSUE TITLE
Saved entities are not returned from queries. 

### ISSUE THREAD

**Issue by dcreeyp2p** [googleapis/nodejs-datastore#172]
When querying for records that were just committed via `datastore.save` I sometimes don't receive the records that were just submitted. I do not receive any failure from the api, nor do I see any conflict on the response.

#### Environment details

  - OS: macOS High Sierra 10.13.4
  - Node.js version: 8.11.3
  - npm version: 5.6.0
  - `@google-cloud/datastore` version: 1.4.1

#### Steps to reproduce

  1. Execute 5 times `this._datastore.save({..., method: 'insert'})`
  2. Wait for inserts to complete successfully (promise.all resolved)
  3. Execute 1 time `this._datastore.createQuery(...).filter({indexedProp: 'ValueContainedInAllInsertedRecords'}).runStream()`
  4. Wait for query to complete successfully (promise resolved)
  5. Repeat steps 1-4 in a loop until the query does not return all expected results. For simplicity you may delete all records after step 4 on each iteration, though this does not effect the outcome.

Each stored record has a unique key. The number of records being returned is well beneath the batch size. The value that is filtered on is indexed. I've tried inducing a delay of up to 30 seconds after inserting the records and before querying; this has no effect. 

#### Expected Results
Query should return all inserted records with the same filtered property.

I expect to find all 5 records on every query. This intermittently fails. Most of the time (90%) I get all 5 records, sometimes I get 3 or 4. I have tried using both `this._datastore.save({..., method: 'upsert'})` and a `transaction` to save the records. I receive the same results any way I try to store the entities.

I've created a repository with the code necessary to reproduce the problem. https://github.com/dcreeyp2p/google-datastore-no-query-response

**Comment by stephenplusplus** [comment]
I've reproduced using your code sample (thank you!), and it seems like this is a case of eventual vs. strong consistency: https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore

I've made some changes to your code that will support strong reads: https://github.com/dcreeyp2p/google-datastore-no-query-response/pull/1
