### ISSUE TITLE
[Docs enhancement/Question]: is order in ArrayValues preserved?

### ISSUE THREAD

**Issue by trollkotze** [googleapis/nodejs-datastore#179]
From small tests I have done, it appears that the order of Array properties in a retrieved entity is preserved in the same order that they were saved.
But I cannot find info in the docs whether this is guaranteed.

#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 9.2.0
  - npm version: yarn 1.3.2
  - `@google-cloud/datastore` version: 1.4.1

#### Steps to reproduce

```
// just some key where we save and retrieve our test entity
let key = datastore.key({
  namespace: 'whatever',
  path: ['ArrayTest', 'something']
});

// save an array of numbers in order
let numbers = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'];
await datastore.save({key, data: {numbers}}); 

// ...

// retrieve that entity later:
let entity = await datastore.get(key);

console.log(entity.numbers);
/* prints out:
 * [ 'zero',
 * 'one',
 * 'two',
 * 'three',
 * 'four',
 * 'five',
 * 'six',
 * 'seven',
 * 'eight',
 * 'nine',
 * 'ten' ]
 */
```

I have only done small tests like this, with up to a few hundred entities and simply save and get. So far I have not seen a case where the retrieved array is ordered differently from how I saved it. But I am not sure if this is guaranteed. I could not find a statement in the docs stating explicitly that order of arrays / list values is preserved in the way they are saved.

I would like to rely on the assumption that order is preserved in that way.

Can someone confirm or reject this assumption?

see also (same question): https://stackoverflow.com/questions/52020863/is-order-preserved-in-arrays-listvalues-in-google-cloud-datastore

**Comment by stephenplusplus** [comment]
StackOverflow and the Google Datastore docs to the rescue!

> "The order of this array may not be preserved if it contains a mix of indexed and unindexed values."
> \- [google.datastore.v1.ArrayValue](https://cloud.google.com/datastore/docs/reference/data/rpc/google.datastore.v1#google.datastore.v1.ArrayValue)
