### ISSUE TITLE
How to retrieve a list of Indexed properties

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-datastore#183]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2855

<a href="/hadiosbourne"><img src="https://avatars2.githubusercontent.com/u/12885513?s=88&v=4" height=44 width=44 align=left></a>@hadiosbourne<br>August 22, 2018 9:21 AM

Currently I have a few properties on my datastore that are indexed and are taking too much space,
I'm planning to run through all the records and remove those properties from the index list,(to save space)

Is there a way to query the the attributes of properties or just to get list of the properties that are indexed?

Then i can run a query on all the records and update that property to be excludeFromIndexes and upsert them again.

Thanks!

**Comment by stephenplusplus** [comment]
<a href="/hadiosbourne"><img src="https://avatars2.githubusercontent.com/u/12885513?s=88&v=4" height=44 width=44 align=left></a>@hadiosbourne<br>August 28, 2018 11:02 AM

Any suggestions guys?

**Comment by hadiosbourne** [comment]
Any ideas guys? Appreciate it

**Comment by vishald123** [comment]
Hi @hadiosbourne, following way you can get a list of indexed properties from your project. Refer `Property queries` from [this](https://cloud.google.com/datastore/docs/concepts/metadataqueries) link.

```js
var {Datastore} = require('@google-cloud/datastore');
var datastore = new Datastore();

async function runPropertyQuery() {
    const query = datastore.createQuery('__property__').select('__key__').limit(20)
    const [entities] = await datastore.runQuery(query);
  
    entities.forEach(entity => {
      const key = entity[datastore.KEY];
      console.log(key)
  
    });
  }

runPropertyQuery();
```

Let me know if this works for you.
