### ISSUE TITLE
code: 2, details: 'Stream removed', note: 'Exception occurred in retry method that was not classified as transient'

### ISSUE THREAD

**Issue by davalapar** [googleapis/nodejs-datastore#187]
#### Error details

```
{ Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (C:\cygwin64\home\1234\projectdir\node_modules\grpc\src\common.js:87:15)
    at Object.onReceiveStatus (C:\cygwin64\home\1234\projectdir\node_modules\grpc\src\client_interceptors.js:1188:28)
    at InterceptingListener._callNext (C:\cygwin64\home\1234\projectdir\node_modules\grpc\src\client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (C:\cygwin64\home\1234\projectdir\node_modules\grpc\src\client_interceptors.js:614:8)
    at callback (C:\cygwin64\home\1234\projectdir\node_modules\grpc\src\client_interceptors.js:841:24)
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  details: 'Stream removed',
  note: 'Exception occurred in retry method that was not classified as transient' }
```

#### Environment details

  - OS: Windows 7 x64
  - Node.js version: 9.8.0
  - npm version: 6.0.1
  - `@google-cloud/datastore` version: 1.4.1

#### Steps to reproduce

I'm using a simple query with filters.

Days ago it never occurs but since yesterday it does happen every once in a while regardless of the table queried or filters used.

The tricky part is I have never encountered this on our prod environment, only on my local dev environment.

I have looked over the following links and I'm getting a hint that this is somehow network related in my case considering that my workstation's internet connection is quite choppy every once in a while (compared to a cloud vm).

* https://cloud.google.com/datastore/docs/concepts/errors
* https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto

Having noticed that when I retry the query after this error occurs, it goes well 100% of the time, my guess is that if the datastore connection ever went dead a couple moments ago and I happen to send a query, my query gets dropped instead of awaiting and piggybacking to the newly established datastore connection.

**Comment by nileshbhoskar** [comment]
I am also getting this issue for below configurations
OS : Ubuntu 16.04
Node : 8.14.0
npm : 6.4.1

**Comment by huaizhuang700** [comment]
Hello, I also made this mistake. Have you solved this mistake?
