### ISSUE TITLE
Improve documentation and tutorial series for CRUD operations

### ISSUE THREAD

**Issue by arunkumar413** [googleapis/nodejs-datastore#188]
Hi Team,

I'd like to use this library for my nodejs application on appengine. Unfortunately the documentation isn't much helpful. I'd like to find the entities by id, update by id, etc,. and there isn't any snippet to show how to achieve this. Could you please write some tutorial series on the common tasks such as CRUD operations that are performed on the database.

Thanks,
Arun

**Comment by davalapar** [comment]
Hi Arun,

I'm not the repo maintainer, but the **How-to Guides** section could be what you're looking for:

* https://cloud.google.com/datastore/docs/how-to

The information provided across the series of pages has allowed our team to:

* Create records
* Read records (individually, or by batch using queries)
* Update records (individually, or by batch using transactions)
* Delete records (individually, or by batch)

I'm confident that by skimming alone across the pages you could easily get up and running with a crud prototype all within less than an hour, or two.

**Comment by arunkumar413** [comment]
I've gone through that doc but it's not much helpful. I'm expecting some codelabs kind of tutorial series.
https://codelabs.developers.google.com/

**Comment by arunkumar413** [comment]
Who ever is writing the documentation should keep in mind the difference between a software developer and software engineer. A developer is similar/analogous to a carpenter. A carpenter can make wooden doors even without learning  botany or anatomy of trees,. Similarly a developer should be able to make something even with out reading the extensive documentation of the product.  Just a good, simple, precise tutorials series are enough for a developer.

**Comment by stephenplusplus** [comment]
@arunkumar413 I believe you could suggest some new ideas for the docs through the "Send Feedback" link on this page: https://cloud.google.com/datastore/docs/how-to. That would make sure it gets to the right people!
