### ISSUE TITLE
Max entities per query?

### ISSUE THREAD

**Issue by davalapar** [googleapis/nodejs-datastore#209]
Hi there, just curious. Is there a max number of entities limit on each datastore query?

Sorry for asking here, the docs is vague saying 1000 limit on Lookup, not sure if that's what I'm looking for.

Thank you.

**Comment by stephenplusplus** [comment]
I don't know of any limits. Our library doesn't impose any, so it should be set by the API, if there is one. You could try to ask this over on https://stackoverflow.com/questions/tagged/google-cloud-datastore.
