### ISSUE TITLE
Cannot connect to the emulator: grpc Connect Failed

### ISSUE THREAD

**Issue by z-vr** [googleapis/nodejs-datastore#23]
#### Environment details

  - OS: OSX 10.12.6
  - Node.js version: v8.9.3
  - npm version: 5.5.1
  - @google-cloud/datastore version: 1.3.0

All debug info here https://github.com/Sobesednik/datastore-emulator-test

#### Steps to reproduce

  1. `git clone https://github.com/Sobesednik/datastore-emulator-test.git`
  1. `cd datastore-emulator-test`
  1. `npm i`
  1. `gcloud beta emulators datastore start --no-store-on-disk`
  1. (new termial) `$(gcloud beta emulators datastore env-init)`  
  1. `npm t`

It works with `@google-cloud/datastore`.

**Comment by stephenplusplus** [comment]
Thanks for going through the trouble to set up the reproduction repo. It's very appreciated! I've been able to reproduce and find the fix. I will have a PR and release shortly.

**Comment by stephenplusplus** [comment]
Released a fix for this in `@google-cloud/datastore@1.3.2`. Please check it out, and let me know if there are any issues.

**Comment by z-vr** [comment]
@stephenplusplus I've checked and it's working now, thank you for the fix!
