### ISSUE TITLE
What is datetime correct format for save and update

### ISSUE THREAD

**Issue by fluke34261** [googleapis/nodejs-datastore#230]
I try to find correct format datetime in datastore

i use new Date() or new Date().toJSON() but datastore still parse to **String** Type

sorry for my english, thankyou

**Comment by fluke34261** [comment]
@stephenplusplus  thank you for reply. Here is my simple code

```
post (req, res, next) {
  let body = Object.assign({}, req.body)
  body['createdAt'] = (new Date()).toISOString() // String in datastore
  body['updatedAt'] = (new Date()).toISOString() // String in datastore
  body['StartTime'] = Math.round((new Date()).getTime() / 1000) // Integer in datastore
  
  const Key = this.datastore.key('User);
  const entity = {
    key: Key,
    data: body
  };
  this.datastore
    .insert(entity)
    .then(() => {
      return res.status(200).json(Key.id)
    })
    .catch(err => {
      return res.status(500).send(err);
    });
}
```

I think i miss understand something. please describe me

**Comment by stephenplusplus** [comment]
Here's an example of inserting, then retrieving a Date value:

```js
'use strict'

const Datastore = require('@google-cloud/datastore')
const datastore = new Datastore()

const entity = {
  key: datastore.key('User'),
  data: {
    createdAt: new Date(),
  },
}

datastore
  .insert(entity)
  .then(() => datastore.get(entity.key))
  .then(resp => {
    const entity = resp[0]
    console.log(entity.createdAt instanceof Date) // true
  })
  .catch(err => {
    console.log(err)
  })
```

I think it's working. How are you finding that it is a string?

**Comment by fluke34261** [comment]
I'm Sorry my word is not clear
I mean when i goto console datastore and looking to type that inserted with `new Date()`
i got String type

<img width="758" alt="screen shot 2561-11-01 at 09 33 05" src="https://user-images.githubusercontent.com/8720628/47829377-c6df2080-ddb9-11e8-984c-263f4f42458a.png">

but i think it should be this

<img width="761" alt="screen shot 2561-11-01 at 09 33 12" src="https://user-images.githubusercontent.com/8720628/47829417-f8f08280-ddb9-11e8-950e-804f1a0c423b.png">

How to insert **Date** with  with ICT format

thank you

**Comment by stephenplusplus** [comment]
Interestingly, my `insert` is stored as "Date and time":

![image](https://user-images.githubusercontent.com/723048/47904706-d3b45080-de5b-11e8-9765-5f1afd9866f4.png)

Did you try with my code snippet I shared in my last post?

**Comment by fluke34261** [comment]
Oh!

You code is work. Then i will change my function like you.

Thank you so much.

**Comment by stephenplusplus** [comment]
Yay! No problem. Glad we got it to work! 👍
