### ISSUE TITLE
Cannot interop with some entities created by the Python App Engine NDB client.

### ISSUE THREAD

**Issue by kalokiston** [googleapis/nodejs-datastore#253]
I have a Python App Engine app that uses the NDB client to persist data into the datastore.

I am building a CLI tool to perform some admin tasks on the datastore which includes updating some entities. I am using the Node client to implement this.

I was surprised to find out however that the NDB client and the Node client store entity data differently, specifically when there are arrays or subobjects among the properties of the entity. The NDB client stores arrays are repeated values, and the the Node client stores them using the "arrayValue" field. Subobjects are stored directly into the entity with the property names like "subobject.subproperty" by the NDB client, but are stored as "embedded entities" using the "entityValue" field by the Node client.

What does this mean in general for interoperability between the two clients? Is it inadvisable to use both? Or are there specific, predictable, (documented?) semantics for the interaction.

The specific issue I ran into was related to excludeFromIndexes. When I get() an entity that has a subobject and write it back, I am not able to exclude indexing on "subobject.subproperty" using excludeFromIndexes. I suspect this is because the Node client interprets this as excluding the property "subproperty" of the embedded entity "subobject" from indexing, but the value returned by get() does not have such an embedded entity but rather the property "subobject.subproperty". 

I will be able to solve the specific issue I have if the client would allow properties that have a "." in the name to be excluded form indexing, but this is not possible currently as far as I can tell.

#### Environment details

  - OS: macos 10.14
  - Node.js version: v8.11.2
  - npm version: 5.6.0
  - `@google-cloud/datastore` version: 2.0.0

**Comment by callmehiphop** [comment]
@kalokiston I actually hadn't even heard of the ndb client until you opened this issue! But after a little bit of digging, I learned that before Datastore was its own API, it was exclusively on GAE as ndb. I'm not sure if this is still true today, but it sounds like the ndb client does not use the actual Datastore API, which might explain why the data is inserted differently. @crwilcox do you have any insights here?

As far as being able to exclude properties from being indexed, this should be possible and I believe we have a [system test](https://github.com/googleapis/nodejs-datastore/blob/master/system-test/datastore.ts#L120) that illustrates exactly how to accomplish this.

**Comment by kalokiston** [comment]
@callmehiphop From what I can tell from the system test, I think you are suggesting that I can exclude properties using `"subobject.subproperty"`. But that is exactly what I tried and it will not work precisely because NDB and the Node client do not agree on how "subobject.subproperty" is stored. Please see the full explanation in the paragraph starting with "The specific issue I ran into" in my original bug report. If that needs further clarification, let me know.
