### ISSUE TITLE
Ship 3.0

### ISSUE THREAD

**Issue by giovannibonetti** [googleapis/nodejs-datastore#260]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - [x] Search the issues already opened: https://github.com/googleapis/nodejs-datastore/issues
  - [x] Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - [x] Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Mac OS X
  - Node.js version: 11.2.0
  - npm version: 6.4.1
  - `@google-cloud/datastore` version: 2.0.0

#### Steps to reproduce

Try to run the first code example in https://cloud.google.com/datastore/docs/reference/libraries

```js
// Imports the Google Cloud client library
const {Datastore} = require('@google-cloud/datastore');

// Your Google Cloud Platform project ID
const projectId = 'YOUR_PROJECT_ID';

// Creates a client
const datastore = new Datastore({
  projectId: projectId,
});
```

You get the following error:
```js
TypeError: Datastore is not a constructor
```

The fix is simple - just remove the curly brackets in the require line:
```js
const Datastore = require('@google-cloud/datastore');
```

A PR fixing the examples will follow shortly...

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the issue!!  This isn't a case of outdated samples, it's a case of master not matching what's actually shipped.  The syntax of the import has changed in master, but we just haven't shipped `3.0` quite yet.  The fix here is to ship a new version :)

**Comment by giovannibonetti** [comment]
I see, thanks for the explanation! 👍

**Comment by JustinBeckwith** [comment]
This shipped 🎉
