### ISSUE TITLE
Cannot connect to the emulator without default credentials file

### ISSUE THREAD

**Issue by z-vr** [googleapis/nodejs-datastore#27]
#### Environment details

  - OS: OSX 10.12.6
  - Node.js version: v8.9.3
  - npm version: 5.5.1
  - @google-cloud/datastore version: 1.3.2

Updated debug info [here](https://github.com/Sobesednik/datastore-emulator-test#google-clouddatastore132-without-default-credentials).

#### Steps to reproduce

  1. `git clone https://github.com/Sobesednik/datastore-emulator-test.git`
  1. `cd datastore-emulator-test`
  1. `npm i`
  1. `gcloud beta emulators datastore start --no-store-on-disk`
  1. (new termial) `$(gcloud beta emulators datastore env-init)`
  1. `unset GOOGLE_APPLICATION_CREDENTIALS`  
  1. `npm t`

This used to work in `@google-cloud/datastore@1.1.0`. If I just want to test locally on the emulator, do I have to have a credentials file now by design?

**Comment by stephenplusplus** [comment]
For me, both 1.3.0 and 1.3.2 returned the "Could not load the default credentials." error.

> If I just want to test locally on the emulator, do I have to have a credentials file now by design?

I don't believe that's the case. I will continue to investigate.

**Comment by stephenplusplus** [comment]
I've found a fix and sent a PR in #28.
