### ISSUE TITLE
Key return in json DataStore

### ISSUE THREAD

**Issue by DerlysF** [googleapis/nodejs-datastore#278]
Hello its possbile i return an key from datastore,
together from another informations?

Exemple, i have an entity in my datastore, that its called James e have 15 years, when i do an request returns me these informations, and no returns me a key of the entity.

Can someone help me?

**Comment by akwirick** [comment]
You can access the key via the `KEY` symbol.  Roughly as follows.
```
import Datastore from '@google-cloud/datastore';

const ds = new Datastore();
const query = datastore.createQuery('MyKind');
const [result] = await datastore.run(query);
const key = result[Datastore.KEY];
```

**Comment by stephenplusplus** [comment]
@chadbr doesn't @akwirick's example show how to get the key? It's possible I'm missing something, apologies in advance for that!

**Comment by chadbr** [comment]
@stephenplusplus - It does not for me - I'm using TypeScript and I can't do an import like this:

``` 
import Datastore from '@google-cloud/datastore';
```
I get this error:

```
src/data/xxx.spec.ts:6:23 - error TS7016: Could not find a declaration file for module '@google-cloud/datastore'. '/xxxxxx/node_modules/@google-cloud/datastore/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/google-cloud__datastore` if it exists or add a new declaration (.d.ts) file containing `declare module '@google-cloud/datastore';`

6 import Datastore from '@google-cloud/datastore';
                        ~~~~~~~~~~~~~~~~~~~~~~~~~
```

Thanks, Chad

**Comment by akwirick** [comment]
That's just typescript complaining that you don't have the types defined for the import.  If you are on a newer version of the library, they should be bundled alongside the package.  If there's a particular reason you need to run an older version, just install the types as a dev dependency from Definitely Typed.  

`yarn install --dev @types/google-cloud__datastore`
... or the npm equivalent

**Comment by callmehiphop** [comment]
I don't think there's anything actionable left to do here, so I'm going to close. Thanks!
