### ISSUE TITLE
datastore.key call silently fails if key is passed in as a string

### ISSUE THREAD

**Issue by iamsellek** [googleapis/nodejs-datastore#295]
#### Environment details

  - OS: Mac OSX Mojave
  - Node.js version: v10.13.0
  - npm version: 6.4.1
  - `@google-cloud/datastore` version: 2.0.0

#### Steps to reproduce

There seems to either be a problem with the datastore.key() function or with the documentation on it. I _think_ it's an issue with datastore.key().

When attempting to get a key from the datastore.key() function, you need to pass in an array with two items: the first is the item kind and the second is the id. The problem is that trying to pass the id in as a string in the second array slot does not return the correct key. Then, when using this incorrect key to make a datastore.delete() or datastore.get() call, the call does not work and no errors are thrown. Parsing the id into an int solves the problem and the correct key is then returned.

It seems odd to me that the id is used as a string everywhere else but this one location (and that much of the documentation on datastore.key() shows a string in that second array slot), which is why I'm filing this as a bug. If this is intended behavior, then I think the documentation on the datastore.key() function should be updated to reflect this or warn the user about this. I only figured this out after stumbling around the documentation for quite some time and finding another example that used an int in that second slot instead of a string. If I'm doing something wrong (which, as incredibly bright as I am, can't _possibly_ be what's happening /s lol), then I'd love to hear what it is!

Thanks so much for your time!

**Comment by stephenplusplus** [comment]
> The problem is that trying to pass the id in as a string in the second array slot does not return the correct key.

In Datastore, a key has two identification types, either a string "name" or a numeric "id". We do type detection on the input to `datastore.key()` to determine which identification type the user intends.

If you know you're using an "id", but you have a string to work with, you can either convert it to a JavaScript Number, or use `datastore.int('string-that-is-an-id')`.

Would that by any chance explain the situation you're running into? If not, could you demonstrate the issue with some code that might help it click for me? Thank you!

**Comment by iamsellek** [comment]
That worked! Thanks so much! Is there any way this can be added to the documentation or something? I never saw any mention of the datastore.int() function anywhere.

**Comment by idevelop** [comment]
@stephenplusplus in current node versions, `Number.MAX_SAFE_INTEGER` is 2<sup>53</sup> - 1. 
The datastore documentation states that IDs are int64, so I think it might be dangerous to suggest using the built-in js Number class, and `datastore.int()` should always be used (perhaps even enforced by the library), otherwise you would get incorrect results for very large IDs. Hope I'm not misreading this.

**Comment by iamsellek** [comment]
I meant is there any way to make it clearer in the documentation that datastore.int() is the function that should be used for this. I never saw any mention of it until this ticket.

**Comment by idevelop** [comment]
@iamsellek oh, I agree with you, my comment was intended for Stephen, as he's indicating that `datastore.key()` and the javascript Number class are both fine to use when you want to explicitly cast a string to a datastore id.

**Comment by iamsellek** [comment]
@idevelop Oh, sorry! I didn't see the @ lol. Thanks, guys!
