### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: The include `google/api/annotations.proto` was not found.

### ISSUE THREAD

**Issue by idevelop** [googleapis/nodejs-datastore#297]
Hey folks, I seem to be hitting this exception with a very simple datastore node.js client. 

Can confirm that the `annotations.proto` file is indeed not there in the `@google-cloud` module folder, the only 3 files in `node_modules/@google-cloud/datastore/protos/google/datastore/v1` are `datastore`, `entity` and `query`. It is however in a `google-proto-files` module which comes as a dependency, but for some reason the code that's supposed to find the proto file never looks there.

#### Environment details

  - OS: macOS 10.14.2
  - Node.js version: 10.15.0
  - npm version: 6.4.1
  - `@google-cloud/datastore` version: 2.0.0

#### Steps to reproduce

  1. Create new project, `npm install --save @google-cloud/datastore`
  2. `npm list` now looks like this: https://gist.github.com/idevelop/21083e97623001bfcc0f70f705979fd7
  3. Write a barebones datastore client:
```javascript
const Datastore = require('@google-cloud/datastore');
const datastore = new Datastore({ projectId: 'whatever' });
const query = datastore.createQuery('Task');
datastore.runQuery(query).then(results => results[0] || []);
```

  4. `node index.js`, get this exception in the console: https://gist.github.com/idevelop/3570db390fff49b2578c2b347485641a

**Comment by idevelop** [comment]
Interestingly, the issue does not happen in a project folder created directly in my home folder, as opposed to within the Dropbox folder. Maybe the Dropbox syncing messes with the node modules, or the fact that there's a whitespace in the path (`Dropbox (Personal)`). Will keep digging.

**Comment by idevelop** [comment]
After a bit of debugging, here's what I found:
- when the project is in `/Users/andreig/datastore`, the `COMMON_PROTO_FILES` list in `google-gax/build/src/grpc.js` is populated correctly
- when the project is in `/Users/andreig/Dropbox (Personal)/github/datastore`, that list is empty.

I suspect that globby, used to expand the `COMMON_PROTO_GLOB_PATTERNS` into files, is getting thrown off by the the parenthesis in the path, probably because it thinks it's some form of pattern to be matched.

**Comment by idevelop** [comment]
Yeah here we go: https://github.com/sindresorhus/globby/issues/81

**Comment by JustinBeckwith** [comment]
With the version sitting on master right now, globby is no longer used to load proto files from disk and it's been replaced with a simple recursive walk.  How about we publish a new version of the library with the latest proto-files, and see if that addresses the issue?

**Comment by JustinBeckwith** [comment]
If this is still an issue - please let us know!
