### ISSUE TITLE
[3.0] Make default exports work again with this one "horrible hack"

### ISSUE THREAD

**Issue by jc275** [googleapis/nodejs-datastore#303]
Here's how `@google-cloud/firestore` avoided breaking changes by [preserving the default export](https://github.com/googleapis/nodejs-firestore/pull/402/files).

Maybe it's suboptimal performance-wise, but surely a deprecation warning would have been preferable to ["Hey, we broke this!"](https://github.com/googleapis/nodejs-datastore/pull/298/files)

**Comment by grant** [comment]
I'm in favor of not having duplicate ways to use libraries ("Horrible hack") and appropriately creating breaking changes with major semver bumps.

**Comment by JustinBeckwith** [comment]
Yeah - this would have been a nice thing to do previously, but it *does* come with a performance cost.  Given the fact that this change landed in a semver major a few releases ago, I am going to go ahead and close this one out.  Thanks!
