### ISSUE TITLE
Promise returning signature missing from transaction.run

### ISSUE THREAD

**Issue by runeh** [googleapis/nodejs-datastore#308]
The typescript signature for `transaction.run` claims that the method returns void. The method can also return a promise due to the use of promisifyAll, but that is not reflected in the signature.

It would be great to have the signature allow using the promise form of the method.

Presumably the same issue applies to all the other promisified methods across the package as well.

#### Steps to reproduce

  1. Write some code that uses a transaction:

```typescript
const store = new Datastore();
const transaction = store.transaction();
transaction
  .run()
  .then(() => {
    // transaction operations
  })
```

Expected result: no type error.
Actual result: type error: `[ts] Property 'then' does not exist on type 'void'. [2339]`

#### Environment details

  - OS: arch linux
  - Node.js version: 10.14.0
  - npm version: 6.4.1
  - `@google-cloud/datastore` version: 3.0.1

**Comment by JustinBeckwith** [comment]
Fixed with #305!
