### ISSUE TITLE
Promise returning signature missing from insert/update/upsert/save

### ISSUE THREAD

**Issue by erandagan** [googleapis/nodejs-datastore#318]
Exactly like #308 but extended for more functions, not just transactions.

#### Steps to reproduce
```ts
const store = new Datastore();
const key = store.key('User');
const entity = {
  key,
  data: {
    name: 'John'
  }
};

await store.insert(entity); // TS2554: Expected 2 arguments, but got 1.
```

The source of the issue is in `request.d.ts`, which contains the callback variation of the `insert` function but does not contain the promise version, which does not require a callback argument and returns a promise.

Note that the same issue also exists for `update`, `save`, `upsert` and `delete`.

**Comment by JustinBeckwith** [comment]
Fixed with #305!
