### ISSUE TITLE
Missing typescript definitions in build dir

### ISSUE THREAD

**Issue by runeh** [googleapis/nodejs-datastore#330]
The typescript definitions in `./proto` are not exported when you build. Thus no typescript code importing datastore will compile. There is a repro repository here: https://github.com/runeh/datastore-lib-testcase

#### Environment details

  - OS: arch linux
  - Node.js version: 10.14.0
  - npm version: 6.4.1
  - `@google-cloud/datastore` version: 3.1.0
  - yarn version: 1.13.0
  - typescript version: 3.3.3

#### Steps to reproduce

  1. In a typescript file, Import the lib: `import { Datastore } from '@google-cloud/datastore';`
  2. Compile it with tsc

Expected result: no type error
Actual result: type error

```
node_modules/@google-cloud/datastore/build/src/request.d.ts:17:24 - error TS2307: Cannot find module '../proto/datastore'.

17 import { google } from '../proto/datastore';
                          ~~~~~~~~~~~~~~~~~~~~

node_modules/@google-cloud/datastore/build/src/transaction.d.ts:17:24 - error TS2307: Cannot find module '../proto/datastore'.

17 import { google } from '../proto/datastore';
                          ~~~~~~~~~~~~~~~~~~~~
```

**Comment by kmturley** [comment]
I'm experiencing the same issue.

You can workaround by copying the definition files from the repo manually:
```
mkdir node_modules/@google-cloud/datastore/build/proto
curl -o node_modules/@google-cloud/datastore/build/proto/datastore.d.ts 'https://raw.githubusercontent.com/googleapis/nodejs-datastore/master/proto/datastore.d.ts'
curl -o node_modules/@google-cloud/datastore/build/proto/entity.d.ts 'https://raw.githubusercontent.com/googleapis/nodejs-datastore/master/proto/entity.d.ts'
```

**Comment by JustinBeckwith** [comment]
Greetings folks!  This was a total 🤦‍♂️ Fix is over in #335 and we'll try to get it out on monday.

**Comment by AlisonVilela** [comment]
+1

**Comment by kirillgroshkov** [comment]
Linking this issue here: https://github.com/googleapis/nodejs-datastore/issues/350
Cause it's not fully fixed - `*.d.ts` files are indeed included, but `types` field in `package.json` is still missing
