### ISSUE TITLE
Datastore is not a constructor (Typescript)

### ISSUE THREAD

**Issue by danielcardeenas** [googleapis/nodejs-datastore#340]
#### Environment details

  - OS: Windows 10
  - Node.js version: 9.11.1
  - npm version: 6.1.0
  - `@google-cloud/datastore` version: 3.1.1

#### Steps to reproduce

  1. Start application
  2. The compilation will fail due to error

A file looks like this:
```typescript
import Datastore = require('@google-cloud/datastore');
...
export const datastore = new Datastore({
  projectId: process.env.PROJECT_ID
});
```
Fires next error:
`TypeError: Datastore is not a constructor`

**Comment by danielcardeenas** [comment]
This is most likely an issue with datastore types

**Comment by danielcardeenas** [comment]
Fixed by modifying `node_modules/google-cloud__datastore/index.d.ts` file: https://gist.github.com/danielcardeenas/da02f81361ee0cbc3ef3ec61caffe60d

Change imports from
```typescript
import Datastore = require('@google-cloud/datastore');
```
to: 
```typescript
import { Datastore } from '@google-cloud/datastore';
```

**Comment by callmehiphop** [comment]
@danielcardeenas as of `v3.1.0` we have been shipping types with the client. Have you tried using those instead of the `@types` package?

**Comment by callmehiphop** [comment]
I'm going to close this since it is likely an issue with the `@types` package. Please let us know if that's not the case!

**Comment by iancrowther** [comment]
I'm hitting the same issue, not too sure how to "using those instead of the @types package".

**Comment by georgemarrows** [comment]
@callmehiphop uninstalling the `@types` package fixed it for me. Thanks for shipping types with this package!
