### ISSUE TITLE
Projection Query: Selecting an array property does not return anything

### ISSUE THREAD

**Issue by acatalina** [googleapis/nodejs-datastore#349]
## Blocked

- [ ] [Seems to be an API problem](https://github.com/googleapis/nodejs-datastore/issues/349#issuecomment-491899054)

---

#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: 8.9.4
  - npm version:
  - `@google-cloud/datastore` version: 1.4.2

#### Steps to reproduce

1. Store an entity with a property containing an array.
2. Make a simple projection query selecting that property
3. Empty

Not sure if it is documented somewhere but I cannot do a projection query and select a property containing array values. Not talking about querying the property itself, only retrieving it.

Thanks!

**Comment by acatalina** [comment]
Hi, sorry to bother you guys just wondering if there is an update relating to this issue?

Thanks!

**Comment by stephenplusplus** [comment]
Sorry for the delay @acatalina. Here's what I've tried:

```js
const key = datastore.key(['Post', 'post1']);

await datastore.save({key, data: {array: [1, 2, 3]}});

const query = datastore.createQuery('Post').select(['array']);

const [posts] = await datastore.runQuery(query);
console.log(posts)
```
```js
[
  { array: 1,
    [Symbol(KEY)]:
     Key {
       namespace: '1553708214975',
       name: 'post1',
       kind: 'Post',
       path: [Getter] } },
  { array: 2,
    [Symbol(KEY)]:
     Key {
       namespace: '1553708214975',
       name: 'post1',
       kind: 'Post',
       path: [Getter] } },
  { array: 3,
    [Symbol(KEY)]:
     Key {
       namespace: '1553708214975',
       name: 'post1',
       kind: 'Post',
       path: [Getter] } }
```

That appears consistent with what the documentation says to expect: https://cloud.google.com/datastore/docs/concepts/queries#projections_and_array-valued_properties

Let me know if I didn't recreate your scenario accurately.

**Comment by acatalina** [comment]
Hi @stephenplusplus, thanks for the response.

Apologies on my mistake, it is to do with array values where values are objects.

```
const key = datastore.key(['Post', 'post1']);

await datastore.save({ key, data: { arrayObject: [{ 1: 1, 2: 2 }] } });

const query = datastore.createQuery('Post').select(['arrayObject']);

const [posts] = await datastore.runQuery(query)
console.log(posts)
```
```
[ [], { moreResults: 'NO_MORE_RESULTS', endCursor: 'CgA=' } ]
````

Thanks again!

**Comment by stephenplusplus** [comment]
Thank you for that update and sorry for the lag. After trying your sample, it seems that our library isn't dropping any data that the API is returning (request/response is below). So, it looks like it's something on the Datastore side. @pcostell would you mind checking this out?

Request body:
```json
{
  "query": {
    "distinctOn": [],
    "kind": [
      {
        "name": "Post"
      }
    ],
    "order": [],
    "projection": [
      {
        "property": {
          "name": "arrayObject"
        }
      }
    ]
  }
}
```

Response body:
```json
{
  "batch": {
    "entityResults": [],
    "entityResultType": "PROJECTION",
    "skippedCursor": {
      "type": "Buffer",
      "data": []
    },
    "endCursor": {
      "type": "Buffer",
      "data": [
        10,
        0
      ]
    },
    "moreResults": "NO_MORE_RESULTS",
    "skippedResults": 0,
    "snapshotVersion": "0"
  },
  "query": null
}
```

Reproduction code:
```js
'use strict'

const {Datastore} = require('@google-cloud/datastore')
const datastore = new Datastore()

;(async () => {
  const key = datastore.key(['Post', 'post1']);

  await datastore.save({
    key,
    data: {
      arrayObject: [
        {
          1: 1,
          2: 2
        }
      ]
    }
  });

  const query = datastore.createQuery('Post').select(['arrayObject']);

  console.log(await datastore.runQuery(query));
})()
```

package.json
```json
{
  "name": "gissue-349",
  "version": "1.0.0",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@google-cloud/datastore": "^3.1.2"
  }
}
```

**Comment by stephenplusplus** [comment]
@JustinBeckwith @bcoe is there a way to promote this to a Datastore team-maintained platform?

**Comment by bcoe** [comment]
@stephenplusplus, looping in @jkwlui, who's team works on the datastore product.

**Comment by BenWhitehead** [comment]
I've created an internal bug for this scenario, and will try to get it escalated to the Datastore team.

**Comment by JustinBeckwith** [comment]
@BenWhitehead sorry to be a pain - would you mind creating the bug here:
https://issuetracker.google.com/issues/new?component=187197&template=0

That way we can link to it here for anyone to follow, and close the github issue out 🙃

**Comment by BenWhitehead** [comment]
New bug here: https://issuetracker.google.com/136015426

**Comment by rockwotj** [comment]
This is expected behavior FWIW. Datastore Mode does not index full map values. So this will never return results. The following query *will* return results.

```
{
  "query": {
    "distinctOn": [],
    "kind": [
      {
        "name": "Post"
      }
    ],
    "order": [],
    "projection": [
      {
        "property": {
          "name": "arrayObject.1"
        }
      }
    ]
  }
}
```
