### ISSUE TITLE
'Error: Stream removed\n at /user_code/node_modules/grpc/src/client.js:554:15'

### ISSUE THREAD

**Issue by Alappin** [googleapis/nodejs-datastore#35]
#### Environment details

  - OS: Google Cloud Functions
  - Node.js version: GCF version
  - npm version: GCF version
  - @google-cloud/datastore version: 1.3.3

#### Steps to reproduce

  1. Perform a query in Datastore within a cloud function e.g.
 
```
const datastore = require('@google-cloud/datastore')({});

module.exports.myFunction = function() {
   datastore.get(key).then()....
}
```

This results in the above error. Same code works fine when run locally in Node (outside of cloud functions). I don't know whether this is more of a Cloud Functions bug or Cloud Datastore bug?

**Comment by tell-y** [comment]
I got same error on my GCF project.
When my code was run at GCF, the code basically success but sometimes failed.
My case was below:
  1. Deployed GCF project as HTTP triggers.
  2. First access the endpoint, my code is failed(crushed). 
      Errors are:
        - `Unhandled rejection`
        - `Error: Stream removed at /user_code/node_modules/@google-cloud/datastore/node_modules/grpc/src/client.js:554:15`
        - `Function execution took 504 ms, finished with status: 'crash'`

After crashed, I accessed to run datastore code then those code success...
But 30 min. ~ few hours later I accessed, sometimes code got the error...

**Comment by stephenplusplus** [comment]
Related issue: https://github.com/grpc/grpc-node/issues/130

@callmehiphop Do we just need to downgrade all of the places we have a `grpc` dependency to `~1.7`?

**Comment by callmehiphop** [comment]
@stephenplusplus I believe that is correct :(

**Comment by stephenplusplus** [comment]
PRs sent:

https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2784
https://github.com/googleapis/gax-nodejs/pull/165

**Comment by dgadelha** [comment]
Anything we can do locally to workaround Google's bureaucracy with updates?

**Comment by Alappin** [comment]
@dgadelha I ended up downgrading to datastore version 1.1.0 for the meantime and I am not seeing the errors in that version. It will be good if there is a more permanent official solution soon.

**Comment by stephenplusplus** [comment]
cc @bricktownseo who reported this in https://github.com/googleapis/nodejs-spanner/issues/76

**Comment by stephenplusplus** [comment]
New and re-installations of `@google-cloud/datastore` should pick up the non-broken version of gRPC now. Please try it out and let me know if there are any issues.

**Comment by dgadelha** [comment]
Updated everything, didn't experience the issue so far.

**Comment by stephenplusplus** [comment]
Great, thanks for testing. Let me know if it reappears.

**Comment by dgadelha** [comment]
Hey Stephen,

I've been now experiencing this issue:

```
Error: Unexpected error while acquiring application default credentials: read ECONNRESET at /user_code/node_modules/@google-cloud/datastore/node_modules/google-gax/node_modules/google-auth-library/lib/auth/googleauth.js:196:35 at /user_code/node_modules/@google-cloud/datastore/node_modules/google-gax/node_modules/google-auth-library/lib/auth/googleauth.js:229:32 at Request._callback (/user_code/node_modules/@google-cloud/datastore/node_modules/google-gax/node_modules/google-auth-library/lib/transporters.js:79:36) at self.callback (/user_code/node_modules/@google-cloud/datastore/node_modules/request/request.js:186:22) at emitOne (events.js:96:13) at Request.emit (events.js:188:7) at Request.onRequestError (/user_code/node_modules/@google-cloud/datastore/node_modules/request/request.js:878:8) at emitOne (events.js:96:13) at ClientRequest.emit (events.js:188:7) at Socket.socketErrorListener (_http_client.js:310:9)
```

**Comment by stephenplusplus** [comment]
Could you open a new issue with details of the versions you're running, the environment you're in, and reproduction code?

**Comment by dgadelha** [comment]
@stephenplusplus opened #39
