### ISSUE TITLE
package.json "types: src/build/index.d.ts" are missing

### ISSUE THREAD

**Issue by kirillgroshkov** [googleapis/nodejs-datastore#350]
I want to use the library in Typescript and consume its types. But `package.json` currently lacks `types: "src/build/index.d.ts` field that will instruct Typescript to use these types. Without it it doesn't matter that you ship `*.d.ts` files - they are not being used in typescript.

Fix should be fairly simple - just add this missing field to `package.json`.

I know it can default to "index.d.ts", but only if it's in root directory. In your case - it's under `build/src/`, that's why it doesn't work by default.

So far was relying on unstable third-party types from `@types/google-cloud__datastore`, cannot wait to start using official types:)

**Comment by JustinBeckwith** [comment]
Greetings!  What version of the package are you using?  I believe we fixed this in https://github.com/googleapis/nodejs-datastore/releases/tag/v3.1.1

**Comment by kirillgroshkov** [comment]
> Greetings! What version of the package are you using? I believe we fixed this in https://github.com/googleapis/nodejs-datastore/releases/tag/v3.1.1

I'm using `@latest` which is `3.1.1`.

If you look at package.json in master (which is same as released 3.1.1) you see that there is no `types` field: https://github.com/googleapis/nodejs-datastore/blob/master/package.json

**Comment by kirillgroshkov** [comment]
Here's example where `types` field is correctly set (from different repo): https://github.com/googleapis/nodejs-logging-winston/blob/master/package.json#L12

**Comment by JustinBeckwith** [comment]
Yeah my brain left my head on this one folks.  Fix is over in #351.

**Comment by kirillgroshkov** [comment]
Thanks for a quick fix!:)
