### ISSUE TITLE
problem when trying to retrieve data from the data store.

### ISSUE THREAD

**Issue by anisbouzahar** [googleapis/nodejs-datastore#37]
Hello, 
this is my first issue on github , i hope i followed the  guidelines right 🤞 ,and would be of some help to the community.
#### Environment details

  - google cloud functions
 - Node.js version: GCF version
  - npm version: GCF version
  - tested it on  @google-cloud/datastore version: 1.3.3 and  1.1.0

#### Steps to reproduce
i can't put my hands on what seems to be the problem,when the cloud functions are  executed they are frequently not returning the data for example the following  function is supposed to return a kind's entity based on the key. 
```Typescript
exports.getEntity = (req, resp) => {
  let id = req.body.id;
  let parsedId = parseInt(id);
  let kind = req.body.kind;
  let theId = (parsedId !== undefined && parsedId.toString().length === id.length) ? parsedId : id;
  let entityKey = datastore.key([kind, theId]);

  datastore.get(entityKey).then((entity) => {
    if (!utils.isEmpty(entity[0])) {
      resp.json(entity[0]);
    } else {
      resp.json({success: false, message: `${kind} not found`});
    }
  }).catch((err) => {
    resp.json({success: false, message: err});
  });
};
```
some times am getting the right entity  and some time am getting : 
```json
{
    "success": false,
    "message": {
        "code": 2,
        "metadata": {
            "_internal_repr": {}
        },
        "note": "Exception occurred in retry method that was not classified as transient"
    }
}
```
any help would be appreciated ,thanks.

**Comment by stephenplusplus** [comment]
The code 2 translates to an HTTP 500 (Internal Server Error). Unfortunately, that doesn't tell us much about what the actual problem is, other than it's the server that understood the request, but wasn't able to fulfill it.

Can you elaborate on the environment? How frequently is the cloud function being executed?

**Comment by anisbouzahar** [comment]
the cloud function is usually called from a mobile app, but tested using POSTMAN and i can't get the entity data from time to time,
![image](https://user-images.githubusercontent.com/11810182/34440266-0174498c-ecac-11e7-9ee1-d9f2c59b6480.png) the function has been executed 6.4k times
and its not the only one that has the problem other cloud functions too, but this one is the one that has the most impact on the app.

**Comment by anisbouzahar** [comment]
@stephenplusplus let me know if you need more information,appreciated.

**Comment by anisbouzahar** [comment]
the issue was the with the id parsing something was differently  wrong with it, we omitted the parsing line and made all the Ids  strings and it fixed it,thank you for your time. 👍

**Comment by stephenplusplus** [comment]
Phew! Sorry I couldn't be more help, but I'm glad you chased down the bug! Come back anytime if you get stuck 👍
