### ISSUE TITLE
Upserting a list of entities causes "too many entity groups" exception

### ISSUE THREAD

**Issue by zemd** [googleapis/nodejs-datastore#374]
#### Environment details

  - OS: macos+docker
  - Node.js version: 11.4
  - npm version: 
  - `@google-cloud/datastore` version: 3.1.2

#### Steps to reproduce

I am trying to upsert multiple entities within one transaction.
```js
    const transaction = datastore.transaction();
    try {
        await transaction.run();
        await transaction.save(entitiesToUpsert); // entitiesToUpsert.length === 29 
        await transaction.commit();
    } catch (error) {
        console.error(error);
        await transaction.rollback();
    }
```
I define `entitiesToUpsert` as a list of entities which have been updated or new ones which have to be created. All ids are uniq and generated in advance for new entities. so all entities has key path `['EntityKind', '123123123123123']`

key for the entities I created with:
 ```js
const key = datastore.key({ 
   namespace: 'MY_NAMESPACE', 
   path: ['EntityKind', datastore.int(newIdGenerated)] // newIdGenerated === '123123123123123'
}); 
```

After executing `commit` I get an error:

```
{ Error: 3 INVALID_ARGUMENT: operating on too many entity groups in a single transaction.
Object.exports.createStatusError (/var/www/html/node_modules/grpc/src/common.js:91:15)
at Object.onReceiveStatus (/var/www/html/node_modules/grpc/src/client_interceptors.js:1204:28)
at InterceptingListener._callNext (/var/www/html/node_modules/grpc/src/client_interceptors.js:568:42)
at InterceptingListener.onReceiveStatus (/var/www/html/node_modules/grpc/src/client_interceptors.js:618:8)
at callback (/var/www/html/node_modules/grpc/src/client_interceptors.js:845:24)
code: 3,
metadata: Metadata { _internal_repr: {} },
details:
'operating on too many entity groups in a single transaction.' }
```

I assume there shouldn't be an error, since I do not use some other Entity Kinds or there is no parent/child relationships.

**Comment by stephenplusplus** [comment]
Hey @zemd, thank you for the detailed issue! I believe the limit is 25 entities per transaction: https://cloud.google.com/datastore/docs/concepts/limits#limits

> Maximum number of entity groups that can be accessed in a transaction | 25
> -- | --

**Comment by zemd** [comment]
@stephenplusplus I believe that I am not updating **entity groups** but **entities** which should be influenced by 

> Maximum number of entities that can be passed to a Commit operation in the Cloud Datastore API	500

am I wrong?

**Comment by zemd** [comment]
@stephenplusplus also just found in documentation https://cloud.google.com/datastore/docs/concepts/transactions#what_can_be_done_in_a_transaction

> Transactions can query or lookup any number of entities. You can create, update, or delete up to **500 entities** in each transaction. The maximum size of a transaction is 10 MiB.

**Comment by stephenplusplus** [comment]
I guess we are stuck on why the API thinks they're entity groups as opposed to unconnected entities.

"an entity group is a set of entities connected through ancestry to a common root element."

There is nothing in common between the entities in `entitiesToUpsert`?

**Comment by zemd** [comment]
> There is nothing in common between the entities in entitiesToUpsert?
@stephenplusplus 
hm... this quite simple entity, but there are a couple embedded entities, which are passed as simple js objects. I assume they count as entity group? right?

**Comment by stephenplusplus** [comment]
Would you be able to whip up a repro case? It doesn't have to use real entities, but just an entity that can mock what you're working with. I might not have the answer, but with that extra info, we can pass it along if necessary to someone from the Datastore team.

**Comment by bcoe** [comment]
@stephenplusplus @zemd I was able to reproduce:

```js
// [START datastore_quickstart]
// Imports the Google Cloud client library
const {Datastore} = require('@google-cloud/datastore');

async function quickStart() {
  // Creates a client
  const datastore = new Datastore();

  // Saves the entity
  const transaction = datastore.transaction();
  try {
    await transaction.run()
    const entities = []
    for (let i = 0; i < 24; i++) {
      const key = datastore.key({
        namespace: 'Person',
        path: ['Triager', datastore.int(i + 9999)]
      })
      transaction.save({
        key: key,
        data: {
          human_name: `Bob ${i}`,
          age: i
        }
      })
    }
    await transaction.commit();
  } catch (err) {
    console.info(err)
    await transaction.rollback()
  }
  // await datastore.upsert(entities);
}
quickStart().catch(console.error);
```

**Comment by stephenplusplus** [comment]
Hmm, for some reason, that runs successfully for me. Maybe we need to loop in someone from Datastore?

**Comment by zemd** [comment]
@bcoe `transaction.save ` is async method, so you might need `await`, and since `for` is not async you probably need to use `for of`

@stephenplusplus there is my sample of entity structure
```
const key = datastore.key({ 
  namespace: 'MY_NAMESPACE', 
  path: ['EntityKind', datastore.int('123123123123123')] // newIdGenerated === '123123123123123'
}); 

const data = {
  settings: [{ hello: 'World' }],
  title: 'New Title',
  tags: [],
  name: 'my name',
  size: { width: '1', height: '2' },
  anotherEntityId: datastore.int('123123123123123')
};

const entity = {
key,
data
}

```

**Comment by stephenplusplus** [comment]
Thanks for that sample. With a Transaction object, `save` is actually not an async method. It just pushes it into a queue until the final call to `transaction.commit()`.

**Comment by zemd** [comment]
> save is actually not an async method

OH! Thanks :) my mistake, now I need to remove all unnecessary `await`s now )))

**Comment by zemd** [comment]
@stephenplusplus I've figured out, embedded entities was limiting my transaction. I've denormalized it and now looks like I don't have such issue. thanks for help! @stephenplusplus and @bcoe

**Comment by adityapol1058** [comment]
> @stephenplusplus I've figured out, embedded entities was limiting my transaction. I've denormalized it and now looks like I don't have such issue. thanks for help! @stephenplusplus and @bcoe

Hi @zemd can you elaborate this denormalization? I'm currently facing a similar issue [](https://github.com/googleapis/nodejs-datastore/issues/1011#issue-1424300234) and would like your help

**Comment by zemd** [comment]
@adityapol1058 I'm not sure I can recall what exactly I was doing in 2019, but I would assume that by denormalization I meant that I moved embedded entity props into the entity itself or split the entity into several and duplicated some data.
