### ISSUE TITLE
Types of datastore.save do not match actual outcome

### ISSUE THREAD

**Issue by MakuraYami** [googleapis/nodejs-datastore#401]
The types of datastore.save() do not match the actual result

The types should probably be

```
save(entities: Entities, gaxOptions?: CallOptions): Promise<[google.datastore.v1.ICommitResponse]>;
```

instead of 

```
save(entities: Entities, gaxOptions?: CallOptions): Promise<google.datastore.v1.ICommitResponse>;
```

#### Environment details

  - OS: MacOS 10
  - Node.js version: 10.15.3
  - npm version: 6.9.0
  - `@google-cloud/datastore` version: 3.1.2

#### Steps to reproduce

  1.  make a typescript file
  2. add the following code:
```
import { Datastore } from "@google-cloud/datastore";
const datastore = new Datastore();
const [result] = await datastore.save({});
```
  3. see the typescript error if your IDE is configured for it, otherwise try compiling with tsc.

```
Type 'ICommitResponse' must have a '[Symbol.iterator]()' method that returns an iterator.
```

**Comment by MakuraYami** [comment]
As a side note to others having the same issue, my current workaround is:

```
// Monkey patch datastore.save to match how they type it
const _save: any = datastore.save.bind(datastore);
datastore.save = async (...args: any[]) => {
  const response = await _save(...args);
  return response ? response[0] : response;
};
```

**Comment by callmehiphop** [comment]
Looks like this has already been fixed, we just need to cut a release. @bcoe I assume we have one coming up soon?

**Comment by bcoe** [comment]
@MakuraYami could you please try `@google-cloud/datastore@4.0.0`, just published a version that I'm hoping has a fix for you (based on @callmehiphop's investigation).

**Comment by MakuraYami** [comment]
`@google-cloud/datastore@4.0.0` solved my issue, thank you!
