### ISSUE TITLE
4.0 docs are missing

### ISSUE THREAD

**Issue by jasonswearingen** [googleapis/nodejs-datastore#414]
#### Steps to reproduce

 https://cloud.google.com/nodejs/docs/reference/datastore/3.1.x/ is the latest api docs I can find.

The NPM package is currently 4.0.  api's such as runQuery() are missing in the docs (though the api function exists and works in the NPM module)

**Comment by bcoe** [comment]
@jasonswearingen :wave: we've started gradually migrating over to a new docs site (with the huge benefit that docs will be published ever time we publish a new version of a module).

You can find the version 4.x docs here:

https://googleapis.dev/nodejs/datastore/latest/
