### ISSUE TITLE
Allow cross group transactions

### ISSUE THREAD

**Issue by kalokiston** [googleapis/nodejs-datastore#416]
I'm porting a Python App Engine project that uses the cloud datastore to Node. The NDB client in the Python App Engine [allows you to specify a transaction as cross group](https://cloud.google.com/appengine/docs/standard/python/ndb/transactions), which allows atomic updates to up to five different entity groups. 

As far as I can tell there is no way to do this using the node client. I found this to be an extremely useful feature. Is this on the roadmap for the node client?

**Comment by JustinBeckwith** [comment]
Greetings @kalokiston! To be honest - there's not a ton of active development happening in this repository right now.  We'd be happy to take a pull request if you're interested though!

**Comment by kalokiston** [comment]
Thats slightly concerning to hear. 

Do you know if the underlying Datastore API even supports cross group transactions? Is there a place where I can find documentation on the API?

**Comment by JustinBeckwith** [comment]
Sure!  You can find a complete API reference here:
https://cloud.google.com/datastore/docs/reference/data/rest/

And the official Cloud Datastore issue tracker is also a great question for a non-language specific question this like this:
https://issuetracker.google.com/savedsearches/559768

Hope this helps!

**Comment by kalokiston** [comment]
Thanks for the links. 

It does not look like the API supports cross group transactions. I've put in a feature request on the issue tracker. Maybe something will come of it.

**Comment by JustinBeckwith** [comment]
Since it's not exposed on the underlying API - I'm going to go ahead and close this out for now.  Let us know how it goes!

**Comment by kalokiston** [comment]
There is better news.

As per: https://groups.google.com/forum/#!topic/gcd-discuss/YiQDESbe3ek. Cross group transactions are supported in the API. In fact, ALL transactions are implicitly cross group. So there is nothing additional to be done. 

This just has not been documented anywhere. 

Hopefully this will make it into the documentation. It's a pretty significant extension of the semantics of transactions. It is a shame that most Datastore users are probably not aware of it.
