### ISSUE TITLE
API documentation totally broken in > 3.x

### ISSUE THREAD

**Issue by ideasculptor** [googleapis/nodejs-datastore#417]
#### Environment details

  - OS: Any
  - Node.js version: Any
  - npm version: Any
  - `@google-cloud/datastore` version: 3.0.x, 3.1.x

#### Steps to reproduce

  1.  Follow links to Datstore API documentation from anywhere in the documentation - github README files or the official Google documentation links, click Classes -> Datastore to end up at: https://cloud.google.com/nodejs/docs/reference/datastore/3.1.x/Datastore
  2. Try to find any documentation of ANY of the common public methods - createQuery(), runQuery(), key(), update(), upsert(), delete(), save(), etc

Pretty much every method mentioned in any example in the documentation refers to methods that don't actually exist in the API documentation (jsdoc links to those methods in classes and methods that are documented just get rendered as bad markdown links).  The methods do exist in the source code, often with numerous overloaded declarations.  It would appear that the doc generator is broken, either failing on non-static methods or failing on instance methods with overloaded declarations in TS.  I didn't do enough analysis to find the common attributes of the missing elements. 

3.0.x has a more complete set of documented methods, but is still missing things like Datastore.key() and Datastore.runQuery(). I have to go back to 2.x documentation to get what appears to be complete docs, but there's really nothing there to make me think those are complete, either, they just have more methods documented than 3.x and nothing obvious appears to be missing at first glance.  

At least some of the missing methods DO have jsdoc comments in the code, and I would expect jsdoc to generate empty/default documentation for undocumented methods, not strip them from the docs entirely.  Meanwhile, datastore has an effectively undocumented API, except for example code, which is fairly lacking in available options and other parameter, return type, and error reporting details.

**Comment by callmehiphop** [comment]
@bcoe I'm guessing this has to do with us moving the docs off the cloud site?

**Comment by ideasculptor** [comment]
> @bcoe ~I'm guessing this has to do with us moving the docs off the cloud site?~ Looks like that was a bad guess, locally the docs generate fine for me, looks like we might just need to re-generate them?

Hmmm - the docs generate without 'errors' for me, too, but they are still lacking in any of the actual methods of Datastore other than static helper methods.  Did you actually look at the generated docs to see if they are complete?

![Screen Shot 2019-05-28 at 10 18 22](https://user-images.githubusercontent.com/484573/58497993-f678c000-8131-11e9-8a2d-e7f697c83871.png)

That's a screenshot of all the Datastore methods and properties that appear in the documentation - it is identical to what shows up in the documentation links, though formatted differently.

**Comment by ideasculptor** [comment]
It feels to me more like a bug in jsdoc or else faulty jsdoc syntax in the source code, which is causing whole methods to be skipped.

**Comment by ideasculptor** [comment]
I tried forcing jsdoc to the version specified in package.json, but that had no impact.

I went back to master, and those docs are rendered correctly, so it is not a jsdoc problem.  It is a problem with the jsdoc syntax in the source code for 3.0.x and 3.1.x or perhaps a difference in how jsdoc is called between the versions.

**Comment by callmehiphop** [comment]
@ideasculptor locally all the methods do show up for me, however I'm building them using the dependencies listed in master and not the versions tagged in 3.x. It may very well be a JSDoc or template issue.

**Comment by ideasculptor** [comment]
Using dependencies from master but running against v3.1.2 code does render the documentation correctly for me, too.  Running `npm i` after checking out that branch causes the broken docs to be rendered instead, so the quick fix is to pull the source and generate local api documentation that way, but be careful to run npm prior to checking out the 3.x version tag.

**Comment by bcoe** [comment]
@callmehiphop, two things worth checking:

1. at what point did we convert to TypeScript, wondering if the last "good" version of the docs was generated prior to this conversion?
2. if TypeScript isn't the culprit, do the docs generate properly using jsdoc@3.5.5 (the first major update to TypeScript in quite some time went out a week ago).

**Comment by callmehiphop** [comment]
@bcoe I tested with jsdoc@3.6.2 and it seems to be working as expected. There is a TypeScript quirk where any overload comments directly above overloads get removed from TypeScript, so usually we have to declare overloads -> jsdoc -> implementation, however if that were the issue I suspect running JSDoc against the releases in question would result in missing documentation.

**Comment by bcoe** [comment]
@ideasculptor it's good to know that running the dependencies on `master` against `3.x` generates appropriate documentation.

We're in the process of moving over to a new docs site, I expect to start cutting over later this week; when we do so, we can make sure to back-fill the 3.x docs for this library.

**Comment by ideasculptor** [comment]
For what it is worth, when attempting to mock a Datastore via jest.mock('@google-cloud/datastore'), the resulting mock is also missing all of those same methods. I was trying to use their mocked() helper which just performs a cast to MockedFunction<Datastore>, but the thing that comes back generates complaints from the IDE about the same missing methods as are missing from the docs.  I haven't tried  regenerating the built package with the dependencies from master to see if that fixes anything, because kludged together code packages are not quite the same thing as kludged together documentation in production code.  I'm reasonably certain that the bug which is breaking jsDoc in 3.x builds is also breaking mocks due to the similarity in behaviour.

**Comment by bcoe** [comment]
@ideasculptor can confirm that these docs look correct:

https://googleapis.dev/nodejs/datastore/latest/

If so perhaps we can close this issue as soon as we update the links in the README.

**Comment by bcoe** [comment]
:wave: I'm going ahead and closing this, because as far as I can tell the methods that were failing to be documented are now documented here https://googleapis.dev/nodejs/datastore/latest/.

Please feel free to reopen if you continue to bump into any issues :+1:
