### ISSUE TITLE
deploy cloud.google.com removing reference to samples/task.js

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-datastore#429]
now that samples have been refactored from `samples/tasks.js`, we should deploy a version of cloud.google.com that references the new sample files.

**Comment by stephenplusplus** [comment]
@bcoe just swimming through some issues. Is there a way I can help with this?

**Comment by bcoe** [comment]
@stephenplusplus I think this is something that would need to be done by a Googler, since it's the internal site.

**Comment by stephenplusplus** [comment]
I’ll be honest, I was partially hoping to help stir up some activity that would steer us towards completion of this issue :)

**Comment by stephenplusplus** [comment]
@bcoe sorry, just wanted to check in on this again. Is this really an issue we need here on this tracker?
