### ISSUE TITLE
Properties excluded from indexes are not retained on cloud datastore update

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-datastore#44]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2796

<a href="/plaisted"><img src="https://avatars2.githubusercontent.com/u/20848495?s=88&v=4" height=44 width=44 align=left></a>@plaisted<br>January 19, 2018 5:52 PM

#### Environment details
 - Google cloud functions.
 - Datestore lib: 1.3.3

#### Steps to reproduce

1. Insert entity with property excluded from index. (eg `entity.foo`)
2. Get property using nodejs library:
```
let result = await datastore.get(entityKey);
```
3. Change different property and update:
```
result[0]["bar"] = "bar";
await datastore.update(result[0]);
```
4. Foo is now included in indexes.

This does not occur using the c# libraries with the same commands. Is there a way to prevent this? I would expect the update to retain the index setup for the entity so that on update `foo` remains un-indexed.

**Comment by stephenplusplus** [comment]
Thanks for reporting this. 

@pcostell is this something we can and should do in the client library? If so, can you advise the right way to ensure we are current with the indexed properties? Thanks!

**Comment by sduskis** [comment]
@ pcostell, I'm going to close this. Please reopen this issue once you add the additional context.
