### ISSUE TITLE
google datastore how to fetch item in an array

### ISSUE THREAD

**Issue by wahlforss** [googleapis/nodejs-datastore#465]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

How can I retrieve and update an element inside an array stored in datastore. I have an entitity called 2019-06-26. This entity have an array called houses. I want to update houses[3] in datastore, how do I do that? I find it impossible to find the right query.

**Comment by stephenplusplus** [comment]
Hello! You can try something like:

```js
const key = datastore.key('2019-06-26')

datastore.get(key, (err, entity) => {
  // Locate and update the property
  entity.houses[3].status = 'PENDING'

  // Save the updated entity to Datastore
  datastore.save(entity, (err) => {
    if (err) {
      console.log('Entity update failed')
      return
    }

    console.log('Entity successfully updated')
  })
})
```

Let me know if there are any issues!
