### ISSUE TITLE
Cloud Run Cold Starts to Datastore Take Tens of Seconds

### ISSUE THREAD

**Issue by chrishiestand** [googleapis/nodejs-datastore#481]
This is a similar issue to here, except slower: https://github.com/googleapis/nodejs-datastore/issues/9

To reproduce the problem I used @JustinBeckwith 's code from here https://github.com/googleapis/nodejs-datastore/issues/9#issuecomment-502489744 as a template.

#### Environment details

  - OS: Cloud Run (hosted)
  - Node.js version: 12.9.0
  - npm version: 6.10.2
  - `@google-cloud/datastore` version: 4.2.0

#### Steps to reproduce

  1. Setup Datastore in a gcp project (creating a test entity is optional)
  2. Setup Cloud Run in a gcp project (you can use this to build a docker image: https://github.com/chrishiestand/cloud-run-datastore-latency-test )
     A. Be sure to populate the env vars KIND and ID
     B. The Cloud Run service account must have datastore access, so add permissions if necessary
  3. Hit the Cloud Run URL in your browser e.g. https://cloud-run-test-xyz-ue.a.run.app/

Look at the getTime that is returned, for me, it is waaay too slow on cold start (ranges from ~15-40 seconds). Warmed containers answer in a reasonable amount of time e.g. ~20-50 milliseconds.

Thanks!

**Comment by chrishiestand** [comment]
How likely is it that this slowness is purely due to auth details? Because a problem with Cloud Run is that it does not allow containers to mount files like GKE does. This means that using `GOOGLE_APPLICATION_CREDENTIALS` is not possible in Cloud Run. @stephenplusplus I saw that you did work to support token auth, so I think you would know - is there any way to load something like `GOOGLE_APPLICATION_CREDENTIALS` from a string instead of a file?

I tried doing this but it didn't work:

```javascript
  // does not work
   const dsOptions = {};
    if (PRIVATE_KEY && CLIENT_EMAIL) {
        dsOptions.options = {
            credentials: {
                client_email: CLIENT_EMAIL,
                private_key: PRIVATE_KEY,
            }
        }
    }
    const datastore = new Datastore(dsOptions);
```

**Comment by chrishiestand** [comment]
Alright, so this does seem to be an auth issue. I made a version that read an env var and writes to a file, then sets that path to `process.env.GOOGLE_APPLICATION_CREDENTIALS`

https://github.com/chrishiestand/cloud-run-datastore-latency-test/tree/google-application-credentials-kludge

The coldstart times in this branch are ~240ms

**Comment by callmehiphop** [comment]
👋 @chrishiestand I think you can authenticate the client via top level `credentials` configuration

```js
const datastore = new Datastore({
  credentials: {
    client_email: CLIENT_EMAIL,
    private_key: PRIVATE_KEY
  }
});
```

**Comment by chrishiestand** [comment]
Thank you @callmehiphop you're right, that works, I had misread the source code.

Strangely in a new branch using CLIENT_EMAIL auth, the cold start time is about 5 seconds.
https://github.com/chrishiestand/cloud-run-datastore-latency-test/tree/option-credentials

**Comment by callmehiphop** [comment]
That seems a little odd to me.

@JustinBeckwith @bcoe I would actually expect supplying the `credentials` object to be slightly faster since this circumvents the need to read a key file.

**Comment by chrishiestand** [comment]
I agree it is odd. I made some time to confirm it. I created a new service account with no permissions and I re-deployed the cloud run test using the no-access service account (using `CLIENT_EMAIL` and `PRIVATE_KEY` auth). The cold start datastore get takes about ~5400ms, subsequent requests cause a ~40ms get.

**Comment by bcoe** [comment]
@callmehiphop I would expect reading a key file to be nearly instantaneous; If I had to guess, I would guess that it's a call to the metadata-URL that's slow. This sounds like an issue worth bringing up with the Cloud Run team in an issue.

**Comment by stephenplusplus** [comment]
Just an update that basically confirms @bcoe's suspicion. The 5 second delay happens during a check in the auth-library that tries to determine the execution environment. Part of that includes checking if it is Kubernetes by pinging the server for a specific property. Instead of returning a 404 right away, which is what we expect, it will take 5 seconds to do so. My first thought was we were improperly retrying the request, but it seems the metadata server is actually that slow to respond with the 404.

**Comment by chrishiestand** [comment]
Since we really care about minimizing cold start times for things like Cloud Run, Cloud Functions, and App Engine, could we improve this and negate the need to contact the metadata server?

To summarize the cold start datastore `get` times by auth method:

1. `GOOGLE_APPLICATION_CREDENTIALS` - kludge where read from env var and written to disk = ~240ms
2. `{credentials: {client_email, private_key}}` - ~5400ms
3. Service account authentication - ~30s

So based on the above, am I right in assuming that the `GOOGLE_APPLICATION_CREDENTIALS` auth method does not need to contact the metadata server? Perhaps then the simplest solution is to allow GOOGLE_APPLICATION_CREDENTIALS  or similarly named variable to be read from an env var instead of requiring it to be at a file path?

**Comment by stephenplusplus** [comment]
The Cloud Run team is taking a deeper look into this, but so far, it appears to be an issue related to the Dockerfile's "node:12-alpine" image. Is it possible to run against the slim image while a fix is being investigated?

**Comment by chrishiestand** [comment]
@stephenplusplus ugh, gotta love those bizarre environmental bugs that make debugging hard. Thanks to you all and the Cloud Run team for looking into it! At the moment, the `GOOGLE_APPLICATION_CREDENTIALS` kludgey workaround is sufficient for me, but I will use another base image if need be later.

**Comment by chrishiestand** [comment]
@bcoe I had a chance to test the new hard-coded IP version - works great. The `{credentials: {client_email, private_key}}` seems to be about the same cold start performance as using `GOOGLE_APPLICATION_CREDENTIALS`

**Comment by bcoe** [comment]
@chrishiestand awesome closing this :+1: let us know if you bump into any similar issue in the future.
