### ISSUE TITLE
Version 1.3.3 is failing

### ISSUE THREAD

**Issue by andynagai** [googleapis/nodejs-datastore#49]
We recently deployed an application and it upgraded to 1.3.3. This version broke our application. Our application resides in google gke environment. When using this version any request to datastore returns no response. It seems that the newer versions have performance issues also. We had downgraded to 1.1.1 and has resolved our problems. Our datastore operations in our application is now alot faster.

#### Environment details

  - OS: Linux
  - Node.js version: 6.10.2
  - npm version:
  - @google-cloud/datastore version: 1.3.3

**Comment by stephenplusplus** [comment]
A similar issue was reported here: https://stackoverflow.com/questions/48565221/the-datastore-save-method-doesnt-return-a-response

I haven't been able to reproduce locally or on Google Cloud Functions. I haven't tested on GKE, but before I do, could you try once more? I'm wondering if a transient dependency had a bug that has now been resolved.

**Comment by andynagai** [comment]
Also our application instance sits behind a Ingress load balancer.

**Comment by andynagai** [comment]
I re-tested v 1.3.3 on our GKE instance and it seems to be working now. Thank you for resolving the issue.
