### ISSUE TITLE
Flag to point to alternative baseUrl when running locally with Functions Framework

### ISSUE THREAD

**Issue by QuantumInformation** [googleapis/nodejs-datastore#493]
Reposted from https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/87

I import the following in my cloud functions and am trying to run it all locally with the functions framework

 ` ds: require('@google-cloud/datastore')(),`

By default ds.baseUrl_ is "datastore.googleapis.com", but when running `gcloud beta emulators datastore` the local store is at `http://localhost:8766/`

my scripts which fire up both emulation:

```
  "emulate:datastore": "gcloud beta emulators datastore start --project realworldgcp",
    "emulate:functions": " forever -c 'node --inspect' node_modules/@google-cloud/functions-framework --target=api ",
```

How do I  update this baseUrl_ when running with FF?

<img width="677" alt="Screenshot 2019-09-11 at 08 05 26" src="https://user-images.githubusercontent.com/216566/64699168-1becc800-d49c-11e9-9ae0-37dab22b1c21.png">

**Comment by callmehiphop** [comment]
👋 @QuantumInformation I'm not too familiar with FF but for emulator usage we usually suggest setting either the `DATASTORE_EMULATOR_HOST` env var or the [`apiEndpoint`](https://googleapis.dev/nodejs/datastore/latest/Datastore.html#Datastore) option. Have you tried either of these methods?

**Comment by QuantumInformation** [comment]
This is my output of the emulator, does it look correct?

➜  gcp-datastore-cloud-functions-realworld-example-app git:(master) ✗ gcloud beta emulators datastore env-init
export DATASTORE_DATASET=realworldgcp
export DATASTORE_EMULATOR_HOST=::1:8766
export DATASTORE_EMULATOR_HOST_PATH=::1:8766/datastore
export DATASTORE_HOST=http://::1:8766
export DATASTORE_PROJECT_ID=realworldgcp

**Comment by callmehiphop** [comment]
I think so, I'm pretty sure the only env var the client respects is `DATASTORE_EMULATOR_HOST` however.

**Comment by QuantumInformation** [comment]
Perfect looks like it worked, will make a youtube video to help others soon

    "emulate:functions": " export DATASTORE_EMULATOR_HOST=http://localhost:8081 && forever -c 'node --inspect' node_modules/@google-cloud/functions-framework --target=api ",

**Comment by stephenplusplus** [comment]
I think we might have an actual issue here when the "DATASTORE_EMULATOR_HOST" variable is in this format: "::1:8766". Our code was expecting something more like "http://localhost:8081". @QuantumInformation, did something get removed somehow from the original "DATASTORE_EMULATOR_HOST" value you shared, or is it really "::1:8766"?

**Comment by QuantumInformation** [comment]
Yeah thats a bug, I saw when updating the cli today

**Comment by QuantumInformation** [comment]
Your current Cloud SDK version is: 259.0.0
You will be upgraded to version: 262.0.0

┌────────────────────────────────────────────────────┐
│         These components will be updated.          │
├────────────────────────────┬────────────┬──────────┤
│            Name            │  Version   │   Size   │
├────────────────────────────┼────────────┼──────────┤
│ BigQuery Command Line Tool │     2.0.47 │  < 1 MiB │
│ Cloud SDK Core Libraries   │ 2019.09.06 │ 11.7 MiB │
└────────────────────────────┴────────────┴──────────┘

**Comment by stephenplusplus** [comment]
Ah, nice that it was caught! All you should need to do, then, is start the emulator, set the env var, and the Datastore lib will figure it out.

> Not sure if I broke smth locally though, opened another terminal and same issue

The issue where the emulator wants you to set "::1:8766", or @google-cloud/datastore can't detect that it should connect to the emulator?

**Comment by QuantumInformation** [comment]
The issue where the emulator wants you to set "::1:8766",

**Comment by stephenplusplus** [comment]
That is strange.

@JustinBeckwith -- is there a way we can pass this confusion along to the relevant team, and maybe see if the new output format is deliberate and something we'd need to support?

**Comment by JustinBeckwith** [comment]
That's super strange.  @stephenplusplus can you start an email thread with me and Ben?

**Comment by QuantumInformation** [comment]
what have I started.... 

)

**Comment by jkwlui** [comment]
That looks like an ipv6 loopback address equiv to localhost.

https://stackoverflow.com/questions/40189084/what-is-ipv6-for-localhost-and-0-0-0-0

**Comment by stephenplusplus** [comment]
#502 can take over for this issue, regarding supporting IPv6 addresses.
