### ISSUE TITLE
Please upgrade dependency google-gax to ^1.5.2

### ISSUE THREAD

**Issue by weipublic** [googleapis/nodejs-datastore#497]
As in the current package.json,  google-gax is only required to be ^1.0.0. However, a change in #485 ([relative changes](https://github.com/googleapis/nodejs-datastore/commit/1cf85ea129e9916ce8bea5551440b0b598ab6709#diff-d0fec121101b8710dd946c6d84dc0f65L100)) requires at least google-gax v1.2.0 (v1.5.2 is the latest version), where the second parameter `filename` in `loadProto` was made optional ([changelog of google-gax](https://github.com/googleapis/gax-nodejs/releases/tag/v1.2.0)). Please update the dependency accordingly. Thanks.

**Comment by callmehiphop** [comment]
👋 @weipublic sorry about the inconvenience! For a quick fix you could try deleting your node modules and any lock files and re-install.

**Comment by bcoe** [comment]
@weipublic did @callmehiphop's recommendation do the trick for you?
