### ISSUE TITLE
runQuery() fails with timeout after some time of inactivity

### ISSUE THREAD

**Issue by rescan-dl** [googleapis/nodejs-datastore#513]
#### Environment details

  - OS: Linux 4.15.0-64-generic #73~16.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
  - Node.js version: v10.16.0
  - npm version: 6.11.3
  - `@google-cloud/datastore` version: 4.3.0

#### Steps to reproduce

  1. Simple app mixing express and datastore:

"use strict";

const { Datastore } = require("@google-cloud/datastore");
const express = require("express");

const ds = new Datastore();

const app = express();

app.disable("etag");
app.set("trust proxy", true);

app.get("/", (req, res, next) => {
  const q = ds.createQuery("Tasks").order("taskName");

  return ds.runQuery(q).then((data) => {
    console.log("Callback from runQuery()");
    let entities = data[0];
    return res.json(entities);
  }).catch((err) => {
    console.log("runQuery() failed:", err.message);
    return next(err);
  });
});

// Basic 404 handler
app.use((req, res) => {
  res.status(404).send("Not Found");
});

// Basic other error handler
app.use((err, req, res, next) => {
  console.log("500 Error:", err);
  res.status(500).send(err.message || "Something is broken!");
});

if (module === require.main) {
  // Start the server
  const server = app.listen("8080", () => {
    const port = server.address().port;
    console.log(`App listening on port ${port}`);
  });
}

module.exports = app;

  2. Start it as usual:
node app

 3. Open in a browser:
http://localhost:8080/

You will get a list of entities.

 4. Wait for more than 5 minutes. Do not stop the webapp and do not use the webapp.

 5. Open in a browser again:
http://localhost:8080/

 6. No results and after some time (very long) you will get the following errors:

runQuery() failed: Retry total timeout exceeded before any response was received
500 Error: { Error: Retry total timeout exceeded before any response was received
    at repeat (./node_modules/google-gax/build/src/normalCalls/retries.js:80:31)
    at Timeout.setTimeout [as _onTimeout] (./node_modules/google-gax/build/src/normalCalls/retries.js:113:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) code: 4 }

 Notes: it's repeatable in the cloud and running locally (all the environment details for the local run).

Thanks!

**Comment by dann95** [comment]
I'm facing the same issue with the exactly 5 minutes of inactivity...

**Comment by dann95** [comment]
using datastore 4.1.4 or under does not reproduces the bug, to be sure that you are using the right version do:
```bash
npm cache clean
rm -rf node_modules/ package-lock.json
```
Change your package json to use exactly version like:
```json
{
    "dependencies": {
      "@google-cloud/datastore": "4.1.4",
    }
}
```
Remember that it must be "@google-cloud/datastore": "4.1.4", and not: "@google-cloud/datastore": "^4.1.4".

And finally, install packages with:
```
npm ci
```
<b>do not use npm install</b>

**Comment by dann95** [comment]
Can you do the test above, @rescan-dl ?

**Comment by dann95** [comment]
> using datastore 4.1.4 or under does not reproduces the bug, to be sure that you are using the right version do:
> 
> ```shell
> npm cache clean
> rm -rf node_modules/ package-lock.json
> ```
> 
> Change your package json to use exactly version like:
> 
> ```json
> {
>     "dependencies": {
>       "@google-cloud/datastore": "4.1.4",
>     }
> }
> ```
> 
> Remember that it must be "@google-cloud/datastore": "4.1.4", and not: "@google-cloud/datastore": "^4.1.4".
> 
> And finally, install packages with:
> 
> ```
> npm ci
> ```
> 
> do not use npm install

well, at first time without package.lock, you must run npm install.

**Comment by rescan-dl** [comment]
@dann95 I know that the older versions don't have the bug. Our other not-very-active webapp uses v4.1.3 without this problem.
Instead of library downgrading I decided to use a different work-around. I moved the global variable

const ds = new Datastore();

to the local scope for every HTTP request.

**Comment by dann95** [comment]
@rescan-dl are you using another @google-cloud libraries ?

**Comment by rescan-dl** [comment]
@dann95 Yes, storage and pubsub.

**Comment by dann95** [comment]
in the company i work we are facing the same issue, and we use a lot of gcloud libs, such as storage, speech, stack driver.. and we see that also fixing datastore lib version we can still have same bug..

**Comment by Kamil7S** [comment]
I can observe the same issue in my project. After 4-5 minutes of inactivity, my queries fails on runQuery().

    "@google-cloud/datastore": "^4.3.0",
    "@google-cloud/error-reporting": "^1.1.2",
    "@google-cloud/storage": "3.3.1",

Moving "new Datastore()" solves the problem but I don't think that this is clean approach. Or maybe it is?

Thanks!

**Comment by dann95** [comment]
@Kamil7S ofc it isn't a nice idea, since datastore have a slow connection time.

**Comment by dann95** [comment]
@mrksbnch as we tested 4.1.4, but are you sure about the version u are installing ? like no ^ in package.json, cache clean, package-lock.json removed?

**Comment by bcoe** [comment]
@alexander-fenster do you think this might be related to some of the `gprc-js` issues we've been seeing recently?

**Comment by alexander-fenster** [comment]
@bcoe Yes, it seems pretty much like that. All the issues that look like "it's all going well but then after some time everything stops working" point to https://github.com/grpc/grpc-node/issues/1064 at this time.

@rescan-dl @dann95 @mrksbnch Can you folks try it with the latest (released just minutes ago) `@grpc/grpc-js` v0.6.6 (just `rm -rf node_modules package-lock.json && npm install`), and let us know if it helps?  If it still fails, running your code with 

```
export GRPC_TRACE=all
export GRPC_VERBOSITY=DEBUG
```

and sharing the results with us will be really appreciated.

**Comment by mrksbnch** [comment]
@alexander-fenster I'm happy to test that. However, I'm not totally sure how the `@grpc/grpc-js` is related to the `@google-cloud/datastore` package. We currently only have a `@google-cloud/datastore` entry in the package.json file. Do we need to add `@grpc/grpc-js` separately?

@dann95 Yes, we updated `package.json` (without ^), `package-lock.json` and no cache. However, we were still seeing errors. We can probably give it a try again.

**Comment by dann95** [comment]
> @alexander-fenster do you think this might be related to some of the `gprc-js` issues we've been seeing recently?

for sure, a developer from our team fixed the problem migrating from npm to yarn and set:
```json
"resolutions": {
    "@grpc/grpc-js": "0.5.0",
    "google-auth-library": "5.2.2"
  }
```

**Comment by dann95** [comment]
> @alexander-fenster I'm happy to test that. However, I'm not totally sure how the `@grpc/grpc-js` is related to the `@google-cloud/datastore` package. We currently only have a `@google-cloud/datastore` entry in the package.json file. Do we need to add `@grpc/grpc-js` separately?
> 
> @dann95 Yes, we updated `package.json` (without ^), `package-lock.json` and no cache. However, we were still seeing errors. We can probably give it a try again.

Well, also if we lock the version of datastore, it dependencies are declarated with "^" so we need to configure a resolution with npx or use yarn...
reference: https://github.com/googleapis/nodejs-datastore/blob/8e026af47b3232ca86c48e0b53ec14a0ea05463c/package.json#L51

**Comment by dann95** [comment]
> @bcoe Yes, it seems pretty much like that. All the issues that look like "it's all going well but then after some time everything stops working" point to [grpc/grpc-node#1064](https://github.com/grpc/grpc-node/issues/1064) at this time.
> 
> @rescan-dl @dann95 @mrksbnch Can you folks try it with the latest (released just minutes ago) `@grpc/grpc-js` v0.6.6 (just `rm -rf node_modules package-lock.json && npm install`), and let us know if it helps? If it still fails, running your code with the following environment variables set:
> 
> ```shell
> export GRPC_TRACE=all
> export GRPC_VERBOSITY=DEBUG
> ```
> 
> and sharing the results with us will be really appreciated.

We will try.

**Comment by mrksbnch** [comment]
@dann95 Thanks, I edited my previous comment: Adding `@grpc/grpc-js` separately (v0.6.6) seems to work for us thus far.

**Comment by Tolgor** [comment]
Using
```
"resolutions": {
    "@grpc/grpc-js": "^0.6.6"
}
```
as a temporary fix, works for me too.

**Comment by alexander-fenster** [comment]
Since v0.6.6 is the latest one, just doing `rm -rf node_modules package-lock.json && npm install` (for those of you who use `npm`) also brings the latest dependencies to you, including `@grpc/grpc-js` v0.6.6.

Thank you folks for confirming that it works for you!

**Comment by dann95** [comment]
working fine @alexander-fenster

**Comment by bcoe** [comment]
@rescan-dl thanks for your patience, and for bringing this to our attention. Let us know if `0.6.6` also does the trick for you, and we can close this issue :+1:

**Comment by rescan-dl** [comment]
@alexander-fenster "just doing rm -rf node_modules package-lock.json && npm install" worked for me. I'm closing the issue.
