### ISSUE TITLE
Duplication of Entities type within entity.ts

### ISSUE THREAD

**Issue by ckknight** [googleapis/nodejs-datastore#523]
This appears to only affect TypeScript 3.7+, as per https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-rc/#local-and-imported-type-declarations-now-conflict

The `Entities` type is imported: https://github.com/googleapis/nodejs-datastore/blob/master/src/entity.ts#L22
And a separate `Entities` type is defined and exported: https://github.com/googleapis/nodejs-datastore/blob/master/src/entity.ts#L1288

TypeScript 3.7.1-rc reports
```
node_modules/@google-cloud/datastore/build/src/entity.d.ts:19:10 - error TS2440: Import declaration conflicts with local declaration of 'Entities'.

19 import { Entities } from './request';
```

**Comment by bcoe** [comment]
@ckknight thanks for putting this on our radar :+1:
