### ISSUE TITLE
I cannot save raw binary properties

### ISSUE THREAD

**Issue by daniel-jozsef** [googleapis/nodejs-datastore#56]
Hey! Thanks for the great job.

I REALLY, REALLY need to save some data as raw binary. Since there is no uint in Datastore, sorting of int64 values is seriously messed up, which means I need to store for example S2 geocells as string values.

This is okay for testing, but in production, 18 bytes (with "0x" included) vs. 8 bytes is a ridiculous overhead. If I save as Datastore.Int, then (0xffffffffffffffff < 1) === true, which is just wrong.

There is no "Binary" class as per the API reference, so I figured the only way I can possibly coerce writing binary is by using node Buffers. It doesn't work. I have no idea how to do binary. If the driver doesn't support it, please add support ASAP.

(Also, as a sidenote, it would be really nice to have support for hex strings on Datastore.Int.)

#### Environment details

  - OS: Ubuntu Linux 16.04
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - @google-cloud/datastore version: 1.3.3

#### Steps to reproduce

  1. Add Buffer as a property to document to be saved
  2. Save document.
  3. Read back document. The Buffer is returned as an embedded entity, when it should be raw binary data.

**Comment by beaulac** [comment]
I'm not able to reproduce this issue. With the following snippet, I'm getting expected behaviour:

```javascript
const ds = require('@google-cloud/datastore')(/* ds config */);

const binary = Buffer.alloc(8, 0xFF);

const binaryRecord = {
    test: binary
};

const key = ds.key(['kind', 'id']);

ds.save({ key, data: binaryRecord })
  .then(() => ds.get(key))
  .then(([entity]) => console.log(entity));

/* Outputs:
{ test: <Buffer ff ff ff ff ff ff ff ff>,
  [Symbol(KEY)]: Key { namespace: undefined, name: 'id', kind: 'kind', path: [Getter] } }
*/
```

**Comment by daniel-jozsef** [comment]
Thanks! Let me try this quickly and compare my results... I was using "insert", not "save", and I used buffer.from(), but those shouldn't be an issue.

**Comment by JustinBeckwith** [comment]
Greetings!  We haven't heard from you for a while.  Is this still an issue?

**Comment by daniel-jozsef** [comment]
Nah, it seems it was just Javascript messing with me. :)
