### ISSUE TITLE
Export types for Key and Entity 

### ISSUE THREAD

**Issue by cgfrost** [googleapis/nodejs-datastore#568]
I would like improved type safety and code readability when working with Key and Entity objects but the Key and Entity types are not easily imported. The current design implies they are not meant to be imported by users but they exist on the Datastore API as return and parameter types. I would like to easily import types for Key and Entity objects.

 **Describe the solution you'd like**
```
import { Datastore, Key, Entity, Query, Transaction } from '@google-cloud/datastore';

const datastore: Datastore = new Datastore({ projectId });
const myKey: Key = datastore.key({ namespace, path: [kind] });
const myEntity: Entity = { key: myKey, excludeFromIndexes, data };
datastore.save(myEntity);
....
```

 **Describe alternatives you've considered**
There are multiple alternatives that can be imported by making deep references in to the datastore client code but this is messy and it's unclear which is the correct type to import. e.g.
```
import { google } from '@google-cloud/datastore/build/proto/entity';
import { google } from '@google-cloud/datastore/build/proto/datastore';
import Entity = google.datastore.v1.Entity;
import Key = google.datastore.v1.Key;
```

 **Additional context**
I have not included my full use case as it's quite long but I basically have helper methods that create Key and Entity objects. They are returning the `any` type which is not ideal, it makes the code less readable and more prone to errors.

**Comment by vicb** [comment]
You can use `ReturnType<Datastore['key']>` as the type of `Key` but I agree that it should probably be exported.

**Comment by vicb** [comment]
As exporting the type should be an easy change, is there any chance this could be done soon ?
Would a PR be accepted ?

**Comment by stephenplusplus** [comment]
> Would a PR be accepted ?

Yes! This seems like an oversight, and a great idea (thanks, @cgfrost!). Thanks for taking the time to offer your help.
