### ISSUE TITLE
decodeIntegerValue throws an error, but it's not caught.

### ISSUE THREAD

**Issue by jamie-pate** [googleapis/nodejs-datastore#588]
#### Environment details

  - OS: Linux
Distributor ID: Ubuntu
Description:    Pop!_OS 19.10
Release:        19.10
Codename:       eoan
  - Node.js version: v10.15.2, v12.14.0
  - npm version: 6.4.1, 6.13.4, yarn 1.19.1
  - `@google-cloud/datastore` version: ^5.0.2 (5.0.3, 5.0.4)

#### Steps to reproduce

Add an integer value into the datastore that won't fit within the bounds of Number.MAX_SAFE_INTEGER

Try to request the data back from the datastore:
```JavaScript
const datastore = new Datastore({...})
const q = datastore.createQuery('sesionState').filter('event', '=', event || '');
datastore.runQuery(q)
```

```
The application will crash due to an uncaught exception:
Error: We attempted to return all of the numeric values, but value 8446744073709552000 is out of bounds of 'Number.MAX_SAFE_INTEGER'.
To prevent this error, please consider passing 'options.wrapNumbers=true' or
'options.wrapNumbers' as
{
  integerTypeCastFunction: provide <your_custom_function>
  properties: optionally specify property name(s) to be cutom casted}
```
Also a typo misspelling of 'custom' here ----^

```
at decodeIntegerValue (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:388:13)
    at Object.decodeValueProto (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:462:23)
    at Object.entityFromEntityProto (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:607:45)
    at Object.decodeValueProto (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:465:31)
    at value.values.map (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:446:57)
    at Array.map (<anonymous>)
    at Object.decodeValueProto (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:446:37)
    at Object.entityFromEntityProto (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:607:45)
    at Object.decodeValueProto (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:465:31)
    at Object.entityFromEntityProto (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:607:45)
    at results.map.result (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:797:32)
    at Array.map (<anonymous>)
    at Object.formatArray (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/entity.js:796:24)
    at Immediate.request_ [as _onImmediate] (/home/jpate/Documents/escaperoom/leaderboard/node_modules/@google-cloud/datastore/build/src/request.js:230:45)
    at runCallback (timers.js:706:11)"
```

It looks like there's nothing that actually catches errors from `entity.formatArray(...)`

**Comment by jamie-pate** [comment]
Caused by this commit
https://github.com/googleapis/nodejs-datastore/commit/6c8cc74820ca7eaab0e08b9cefac11095c466256

**Comment by bcoe** [comment]
@jamie-pate :wave: thanks for the bug report, do you have a work around for the time being?

**Comment by jamie-pate** [comment]
The work-around so far is to add `{wrapNumbers:true}` as the options for every single `datastore.get(key, options)` or `datastore.runQuery(query, options)` call in my code base.

**Comment by jamie-pate** [comment]
Sample data that causes the issue:

![image](https://user-images.githubusercontent.com/682658/74194969-25c35480-4c0f-11ea-8f07-da8b96a5180c.png)

**Comment by AVaksman** [comment]
@jamie-pate Currently this is intended behavior. Due to js limitations (52 bit safe integer) this library by default will throw an error while attempting to get an an out of bounds integer value from datastore.

This library offers two options to accurately obtain an out of bounds integer value.

1. Pass  `{wrapNumbers:true}` in options
    - as a result the numeric value will be returned as `datastore` [Int](https://googleapis.dev/nodejs/datastore/latest/Int.html) object in which 
      - calling `#valueOf` will attempt to convert the value to `Number` and will throw aforementioned error if the value is out of bounds.
      - calling `#value` will return the numeric value as a string.
2. Pass `wrapNumbers` as [`IntegerTypeCastOptions`](https://googleapis.dev/nodejs/datastore/latest/global.html#IntegerTypeCastOptions) in options. 
    - You can pass your own function that will convert integer value obtained from datastore
    - As an added benefit you can also pass name(s) of properties who's values should be converted using your own provided function. (by default all integer values will be converted using provided function)
```ts
function myFunc(value) {
  console.log(value);
}

datastore.runQuery(q, {
  wrapNumbers: {integerTypeCastFunction: myFunc},
});
```

**Comment by jamie-pate** [comment]
The issue isn't the throwing part, it is the transition between exception based error handling and stream/callback based error handling.

The caller of `entity.formatArray(...)` is a stream event handler which uses the nodejs callback style error handling.

When the error is thrown it is never caught. The consumer (my code) has no chance to handle the error (other than the uncaught exception handler) and the original call site will never finish because the callback is never called.

It's extra confusing when you add promisify around the original `.get()` or `.runQuery()` and the promise never completes.

This isn't the real problem because if you do not have an uncaught exception handler the process will exit with an error code!!! (And the stack trace provided is useless on a production system)

**Comment by jamie-pate** [comment]
Also, the originally stored number appears to have been inserted as a JavaScript float as a member of a plain JavaScript object. In this  closed JavaScript only system the precision loss had already happened long before the data was passed to the library for storage in the first place. I'm not sure what the value is of testing application data when deserializing. In this case the value is larger than the data type can store without loss of precision, but the precision was already lost. Checking the value is not an accurate measure of data loss. The code should really check if the value is oversized, then convert the value to number and back and compare the result. Only then can you say that the conversion actually list any precision!

**Comment by ewjordan** [comment]
+1 on @jamie-pate's last comment, which bit me recently: it's highly unexpected that an upsert will write without complaint but reading back the same data will throw. It seems like either both should fail (or require that a flag is passed) or neither.

**Comment by AVaksman** [comment]
Integer value outside of the bounds of a JavaScript Number object can be uploaded using an [`Int`](https://googleapis.dev/nodejs/datastore/latest/Int.html) object by passing the numeric value as a string to [`Datastore.int(numercValueAsString)`](https://googleapis.dev/nodejs/datastore/latest/Datastore.html#.int)

**Comment by jamie-pate** [comment]
It could be, but it wasn't in this case, it was just a very large float as the property of some javascript object which was submitted as a value. (It had already been rounded, so `GIGO` is the expectation)

I also noticed that there's no `options` parameter for `query.runStream()` which also crashes the program when it encounters these large values.

**Comment by jamie-pate** [comment]
the type for `IntegerTypeCastFunction` could also be `(value: number | string | ValueProto) => any` instead of `Function` :cry:

**Comment by chadbr** [comment]
This is breaking all our code also...

We store our dates at UTC unix timestamps...

```typescript
export interface SomeInterface extends Bla {
  ...
  startTime?: string;
  endTime?: string;
}
```

These are all failing to read now as they're being interpreted as integers instead of strings... This is in pretty much every table we have.

The very concerning bit is the value being passed out by the error message doesn't match the value in datastore...

For example:

```
A 2020-02-24T20:01:49Z /app/node_modules/@google-cloud/datastore/build/src/entity.js:388
A 2020-02-24T20:01:49Z             throw new Error('We attempted to return all of the numeric values, but ' +
A 2020-02-24T20:01:49Z             ^
A 2020-02-24T20:01:49Z 
A 2020-02-24T20:01:49Z Error: We attempted to return all of the numeric values, but value 158257445394400000 is out of bounds of 'Number.MAX_SAFE_INTEGER'.
A 2020-02-24T20:01:49Z To prevent this error, please consider passing 'options.wrapNumbers=true' or
A 2020-02-24T20:01:49Z 'options.wrapNumbers' as
A 2020-02-24T20:01:49Z {
A 2020-02-24T20:01:49Z   integerTypeCastFunction: provide <your_custom_function>
A 2020-02-24T20:01:49Z   properties: optionally specify property name(s) to be cutom casted}
```

But all the values in the table are of this magnitude:

```
createdDate
1582572895389
endTime
1582572928080
startTime
1582572921680
updateDate
1582572928080
```

The parsing seems to be adding several 0's onto the integers...

-- Rolling back to 4.x for now.

Thanks, Chad

p.s. for what it's worth - this behavior is unacceptable to me... I'd prefer a rollback of this change.

**Comment by AVaksman** [comment]
@chadbr 
I have tested with the following code snippet and it worked.
```ts
      const postKey = datastore.key('Work');
      const data = {
        work: 'Initial work',
        inProcess: true,
        finished: false,
        createdDate: new Date().getTime(),
        startTime: Date.now(),
      };
      await datastore.save({key: postKey, data});

      const transaction = datastore.transaction();
      await transaction.run();
      let [entity] = await transaction.get(postKey);
      entity.work = 'Updated work';
      entity.updateTime = Date.now();
      entity.inProcess = false;
      entity.finished = true;
      transaction.update(entity);
      await transaction.commit();

      await datastore.merge({
        key: postKey,
        data: {work: 'Finished work', endTime: new Date().getTime()},
      });

      [entity] = await datastore.get(postKey);
      console.log(entity);
```

```ts
  inProcess: false,
  updateTime: 1582668202457,
  finished: true,
  endTime: 1582668202556,
  startTime: 1582668201555,
  createdDate: 1582668201554,
  work: 'Finished work',
```

Could you please share you repro data or code snippet that causes the aforementioned issue.

Please also share your
#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/datastore` version:

**Comment by jamie-pate** [comment]
It sounds like his timestamps are more like `"158257445394455555"` (where 55555 is the sub-millisecond part?). Though this isn't technically a "Unix timestamp" since those are counted in seconds :)

**Comment by chadbr** [comment]
I was wrong before (log messages truncated the Kind name)... but I tracked it down last night.

We have some code that is ensuring ordered, unique id's by appending a manually incremented order onto a timestamp:

```
          order: Number(logMessage.timestamp.toString() + (this.order++).toString().padStart(5, '0'))
```

A number is used so it can be queried with `.filter('order', '>', order);`

Works fine up to 4.4.1, breaks after.

I'm sure we have similar issues elsewhere... hard to say without lots of testing.

What is the recommendation here? I'm not sure potentially crashing a process with unhanded exception is the way to go?

Thanks, Chad

**Comment by chadbr** [comment]
p.s. I can write some code to do the same if it helps...

**Comment by chadbr** [comment]
@AVaksman what is the expected behavior now?
