### ISSUE TITLE
GET 'id' - (JSON) output

### ISSUE THREAD

**Issue by RFlintstone** [googleapis/nodejs-datastore#597]
Hi all,

I'm trying to prevent a double post/create from happening with a simple if statement and the GET function. I was wondering if I also could output the 'id' with express.js.

Currently I have:
```
{
"created_at": "26-02-2020 - 14:34:40",
"name": "{name}",
"description": "{desc}",
"price": "999"
}
```
And I would like:
```
{
"id": "{id}"
"created_at": "26-02-2020 - 14:34:40",
"name": "{name}",
"description": "{desc}",
"price": "999"
}
```

Thanks in advance
~Ruben

**Comment by RFlintstone** [comment]
I solved it with an extra function which converts the entities to objects and some extra code in the read/GET method. I will post a part of my code here however I would like to know if there is a better/shorter way to solve the problem.


What merges all (Datastore) properties into one JSON object:
```
        let allTasks = [];
        for (const task of tasks[0]) {
            allTasks.push(entity_to_obj(task));
        }
        if (allTasks.length === 0) {
            allTasks = [{"id":"-","status":"No data"}];
        }
        return allTasks;
```
On POST I check if the ID that is asked for already exists in the database with the help of the properties that are now in one JSON object that I get with the GET method / read function. If it doesn't exist it creates an entry if it does already exists it spits out a custom JSON object that tells the code that there is no data yet with that specific ID.
```
        if (allTasks.length === 0) {
            allTasks = [{"id":"-","status":"No data"}];
        }
```
I'm still curious if there is any shorter way to merge all properties into one JSON object without an extra function.

**Comment by crwilcox** [comment]
Hi @RFlintstone . I may not understand what your function is doing. Here is a sample adding and getting an entity, and its key.

```

// Imports the Google Cloud client library
const {Datastore} = require('@google-cloud/datastore');

// Creates a client
const datastore = new Datastore();

const kind = "Grocery"

/*
 * Adds an entity to datastore. Should not fail, assuming no conflicts
 */
async function add(name, price) {
  // The Cloud Datastore key for the new entity
  const itemKey = datastore.key([kind, name]);

  // Prepares the new entity
  const item = {
    key: itemKey,
    data: {
      description: 'milk',
      price: price
    },
  };

  // Saves the entity
  var response = await datastore.save(item);
  console.log(`Add ${item.key.name}: ${item.data.description} ${item.data.price}`);
}

async function get(name) {    
    const itemKey = datastore.key([kind, name]);
    var items = await datastore.get(itemKey);
    var item = items[0]
    console.log(`Get ${item[datastore.KEY].name}: ${item.description} ${item.price}`);
}

async function main() {
    await add("milk", 2.99)
    await get("milk")
    await add("milk", 3.99)
    await get("milk")
}  

main()

```
which would result in the following when run:
```
Add milk: milk 2.99
Get milk: milk 2.99
Add milk: milk 3.99
Get milk: milk 3.99
```

**Comment by stephenplusplus** [comment]
@RFlintstone please let us know if there's more we can do!
