### ISSUE TITLE
markDone() called from .then() does not work

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-datastore#60]
Reported by @sudiptachatterjee: https://stackoverflow.com/questions/48894883/google-cloud-datastore-lookup-and-update-in-one-transaction

The user claims that when markDone() is called for the task from the .then() handler it does not work. The output of that snippet is:

```
Calling markDone with task Key ID 5654313976201216
Updated task
Result is [ undefined ]
```

When markDone is called with the given task ID directly it seems to work.
@stephenplusplus / @callmehiphop , do you have ideas what could go wrong here?

**Comment by beaulac** [comment]
Shouldn't all these functions (the functions in the [sample](https://github.com/googleapis/nodejs-datastore/blob/master/samples/tasks.js) as well as the user's code) actually return their promises? Otherwise it's race conditions everywhere.

**Comment by stephenplusplus** [comment]
@callmehiphop and @sudiptachatterjee have worked this out offline (noted in the SO answer: https://stackoverflow.com/questions/48894883/google-cloud-datastore-lookup-and-update-in-one-transaction)
