### ISSUE TITLE
@google-cloud/datastore statistics queries not working

### ISSUE THREAD

**Issue by Anas2612** [googleapis/nodejs-datastore#662]
```
const { Datastore } = require("@google-cloud/datastore"); //version ~5.1.0
class DatastoreRepository {
  constructor() {
    this.datastore = new Datastore({
      projectId: PROJECT_ID,
      namespace: NAME_SPACE
    });
  }

async getStats(entityName){
const query = this.datastore.createQuery("__Stat_Kind__");
await this.datastore.runQuery(query);
//my code here
}
}
```

getting this response   

```
[ [],
  { moreResults: 'MORE_RESULTS_AFTER_LIMIT', endCursor: 'CgA=' } ]

```
i m new to datastore and doesn't find any answer to the statistic with nodejs client

let me know if i am doing something wrong , __Stat_Total__  is also giving empty result

**Comment by laljikanjareeya** [comment]
Datastore has statistics which are generated on a daily basis. [The Datastore documentation](https://cloud.google.com/datastore/docs/concepts/stats) has information about all the different statistics about the data stored for an application.

Here is complete working Example on __Stat_Kind__:
```ts
import { Datastore } from "@google-cloud/datastore";

async function runStats() {
    const datastore = new Datastore({
        keyFilename: 'keyfile.json',
        projectId: 'PROJECT_ID'
    });

    const query = datastore.createQuery(['__Stat_Kind__']);

    var [result] = await datastore.runQuery(query);

    console.log('result: ', result);
}

runStats().catch(console.error)
```

**Comment by Anas2612** [comment]
@laljikanjareeya , thanks for the answer, it worked 😀
I was passing the kind into the query incorrectly, 
`'__Stat_Kind__'` but its `['__Stat_Kind__']`
