### ISSUE TITLE
Error: {}You need to pass auth instance to use gRPC-fallback client in browser. Use OAuth2Client from google-auth-library.

### ISSUE THREAD

**Issue by zyuzon24** [googleapis/nodejs-datastore#663]
Hello, I'm working with Google Cloud for the first time, and I'm building a React application. I've created a Datastore entity on GCP and now I'm trying to use the Datastore API in React to request the data to use in the application.

In one file called `action.js` I have:
```
const {Datastore} = require('@google-cloud/datastore');

const datastore = new Datastore({
  projectId: '[project-id]',
  keyFilename: '[file-name]'
});

export const getAllStocks = async () => {
  try {
    var query = datastore.createQuery(['Stock']);
    datastore.runQuery(query, (err, stocks) => {
      console.log('Here is the stocks', stocks);
    });
  } catch (err) {
    console.error('getAllStocks ERROR:', err);
  }
}
```

And I've also tried providing the service account credentials through the environment variable as described [here ](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually) instead of providing the `keyFilename` in the above code

I try to import `getAllStocks` into another file:
```
import React from 'react';
import { getAllStocks } from '../actions';
class StockList extends React.Component {

  render() {
    return [code here]
  }
}
```
However, I get the error `Error: {}You need to pass auth instance to use gRPC-fallback client in browser. Use OAuth2Client from google-auth-library.` when I run the app `npm start`.
And the error disappears once I comment out the line that imports `getAllStocks`

Am I providing the credentials incorrectly? Or is there something else I need to do to resolve the issue?

**Environment details**

- OS: macOS Mojave 10.14.1
- Node.js version: v14.1.0
- npm version: 6.14.4
- @google-cloud/datastore version: 5.1.0

**Comment by laljikanjareeya** [comment]
@zyuzon24  This module was built specifically for Node.js. [Here](https://github.com/googleapis/nodejs-dialogflow/issues/405#issuecomment-529713296) explain how to use `google-auth-library` with any front-end environment such as a browser, Electron app, React,
