### ISSUE TITLE
Saving doesn't work even though objects are properly merged

### ISSUE THREAD

**Issue by RFlintstone** [googleapis/nodejs-datastore#670]
I'm trying to save an entry with the help of '[deep-assign](https://www.npmjs.com/package/deep-assign)' and Datastore (I'm running Express.js on GCP's functions/api endpoint service) to merge the data I want to save but each time it seems to give me an error (I tried datastore.save() some time ago and it should work, unless there was an update I'm not aware of?). Does anybody see why this goes wrong? This is my code: 
```
// createdAtTimestamp.                                                                                                  ||
const months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"];
const d = new Date();
const Timestamp = d.getDate() + '-' + months[d.getMonth()] + '-' + d.getFullYear() + ' - ' + d.getHours() + ':' + d.getMinutes() + ':' + d.getSeconds();
const TimestampString = Timestamp.toString();

module.exports = {
    post: async function (KIND, body) {
        const name = body.id; // The name/ID for the new entity.
        const taskKey = datastore.key([KIND, name]); // The Cloud Datastore key for the new entity.
        const setData = {
            created_at: TimestampString,
            updated_at: "-"
        }
        const loadData = deepAssign(setData, body); // Merge setData and body so it can be called as one object
        const task = // Set (save) task with a task key and the merged data
            {
                key: taskKey,
                data: loadData
            };
        await datastore.save(task, (err, entity) => { // Save merged data with appropriate task key
            if (err) {
                result = err;
            } else {
                result = task;
            }
        })
        return result;
    },
}
```

**Comment by vishald123** [comment]
Hey @RFlintstone, I think the problem is with the **result** variable.

```js
        await datastore.save(task, (err, entity) => { // Save merged data with appropriate task key
            if (err) {
                result = err;
            } else {
                result = task;
            }
        })
        return result; // **Here** 
```

It is out of scope. That could be the problem. try following way and let me know if it works.

```js
        await datastore.save(task, (err, entity) => { // Save merged data with appropriate task key
            if (err) {
                result = err;
                return result;
            } else {
                result = task;
                return result;
            }
        })
```

**Comment by RFlintstone** [comment]
> Hey @RFlintstone, I think the problem is with the **result** variable.
> 
> ```js
>         await datastore.save(task, (err, entity) => { // Save merged data with appropriate task key
>             if (err) {
>                 result = err;
>             } else {
>                 result = task;
>             }
>         })
>         return result; // **Here** 
> ```
> 
> It is out of scope. That could be the problem. try following way and let me know if it works.
> 
> ```js
>         await datastore.save(task, (err, entity) => { // Save merged data with appropriate task key
>             if (err) {
>                 result = err;
>                 return result;
>             } else {
>                 result = task;
>                 return result;
>             }
>         })
> ```

Problem solved! It turned out that I tried to parse an object which was already parsed and that made it drop the connection. I removed JSON.parse() and now it works fine. Both the solutions are working like a charm now! Thank you!!
