### ISSUE TITLE
Add support for exporting the datastore.

### ISSUE THREAD

**Issue by jacob-qurika** [googleapis/nodejs-datastore#672]
**Is your feature request related to a problem? Please describe.**
I'm trying to programmatically initiate a [datastore export](https://cloud.google.com/datastore/docs/reference/admin/rest/v1/projects/export), but the client does not provide an API to do this.

 **Describe the solution you'd like**
Have direct support for exporting in the client library.

 **Describe alternatives you've considered**
I have tried exporting using the REST API directly, but I'm not able to figure out how to authenticate using a service account. Any guidance on how to do this would be appreciated. As far as I can tell the [documentation](https://cloud.google.com/docs/authentication/getting-started?hl=sk) only talks about how to use service accounts with the client library, and not while making a REST call directly.

**Comment by zamnuts** [comment]
Thanks for the feature request @jacob-qurika!
Implementing this feature via RPC is in progress via #685 as part of more features related to the datastore v1 admin API.

**Comment by AVaksman** [comment]
I believe the requested functionality has been added in #734 and released in `v 6.2.0`.
Please feel free to reopen if you still experiencing an issue
