### ISSUE TITLE
vuln: Prototype Pollution and ReDoS introduced via google-gax@0.15.0

### ISSUE THREAD

**Issue by anishkny** [googleapis/nodejs-datastore#69]
Snyk reports vulns:

 1. Prototype Pollution - Vulnerable module: hoek - Introduced through: google-gax@0.15.0
 1. Regular Expression Denial of Service (ReDoS) - Vulnerable module: protobufjs - Introduced through: google-gax@0.15.0

See: https://snyk.io/test/npm/@google-cloud/datastore

#### Environment details

  - OS: Any
  - Node.js version: Any
  - npm version: Any
  - @google-cloud/datastore version: 1.3.5

#### Steps to reproduce

N/A

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/gax-nodejs/issues/200.
