### ISSUE TITLE
Good Documentation

### ISSUE THREAD

**Issue by Bug-Reaper** [googleapis/nodejs-datastore#729]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Documentation is hard to access and incomplete. Lacks some super basic things.
 **Describe the solution you'd like**
1. The link at the top of readme that's labeled documentation should directly link you to the [developer documentation](https://cloud.google.com/datastore/docs), not to wherever it goes now:
![Screenshot_2020-09-19_01-29-22](https://user-images.githubusercontent.com/31227781/93662874-3b57f280-fa18-11ea-94b6-3c7db2629d69.png)

2. Documentation should cover the basics of retrieving a key from an entity acquired from a query. This isn't straightforward at all (`queryResult[0][0][datastore.KEY])`). See [this issue thread](https://github.com/googleapis/google-cloud-node/issues/1768) from 2016 which is being used as your current best documentation:
https://github.com/googleapis/google-cloud-node/issues/1768

Retrieving a key from an existing entity you queried is very likely to be required knowledge for utilizing `upsert` or `update` and it should be covered in the documentation here:
https://cloud.google.com/datastore/docs/concepts/entities#updating_an_entity

More information on keys in general would be welcome too. It's not that complicated, they have a `namespace`, `kind`, `id`, and `path`. Certain properties are optional like `id` and can be omitted to create a very general key for pulling all entities of a certain kind.

 **Describe alternatives you've considered**
Leave it as is and keep framework difficult for newcomers, but yolo fuck documentation anyways amirite?

 **Additional context**

**Comment by crwilcox** [comment]
Hi @Bug-Reaper , there are quite a few issues in here, and it is generally difficult to multithread bugs. I updated the link to the datastore documentation so that one should be 👍.

I would suggest breaking this up into a few issues so the resolution can be tracked separately.

**Comment by meredithslota** [comment]
Hi @Bug-Reaper — we've made some changes since this issue was filed (you were not alone in your complains re: documentation) — now developer docs are also centralized on cloud.google.com (Datastore is here: https://cloud.google.com/nodejs/docs/reference/datastore/latest) and we're working on getting Datastore code samples added to our overall code sample browser here: https://cloud.google.com/docs/samples (which cross-references code samples with other documentation). I'm gonna go ahead and close this out but please feel free to file a new issue with additional feedback.
