### ISSUE TITLE
Is there a document explaining the error code?

### ISSUE THREAD

**Issue by stegano** [googleapis/nodejs-datastore#737]
Can i get an explanation of the error code?

I found a `code` field that can identify the error in the error object as shown in the source code below. But I can't figure out all the code values used in this field. Is there a document explaining the error code values?

#### Environment details

  - OS: MacOS Catalina 10.15.3
  - Node.js version: 10.21.0
  - npm version: 6.14.4
  - `@google-cloud/datastore` version: 6.1.1

#### Steps to reproduce

```ts
...
try {
  const taskKey = datastore.key('something', 'test');
  await datastore.insert({key: taskKey, data: { text: 'hello' }); // <- 1). This data will be added.
  await datastore.insert({key: taskKey, data: { text: 'hello' }); // <- 2). An error occurs because data with the same key already 
  exists.
} catch(e) {
  // An error occurs due to the run of (2), and a value of `6` is transferred to the `code` field of the error object.
  console.log(e.code); // ⇒ output: 6
}
```

**Comment by laljikanjareeya** [comment]
@stegano Please refer the document [Errors and Error handling](https://cloud.google.com/datastore/docs/concepts/errors) for datastore.

**Comment by stegano** [comment]
@laljikanjareeya Thanks for your answer! 😁
