### ISSUE TITLE
Datastore(v. 6.2.0) fails to compile with Typescript(v. 3.7.4) 

### ISSUE THREAD

**Issue by ps-rruiz** [googleapis/nodejs-datastore#746]
Hello, I'm having issues compiling the datastore package in my application. I had to revert to v5.1.0, and that solved the compiling issue.

When compiling, this is the output:
```bash
$ tsc --project ./tsconfig.server.json
node_modules/google-gax/build/src/fallback.d.ts:119:10 - error TS1005: 'from' expected.

119 export * as protobufMinimal from 'protobufjs/minimal';
             ~~

node_modules/google-gax/build/src/fallback.d.ts:119:13 - error TS1005: ';' expected.

119 export * as protobufMinimal from 'protobufjs/minimal';
                ~~~~~~~~~~~~~~~

node_modules/google-gax/build/src/fallback.d.ts:119:29 - error TS1005: ';' expected.

119 export * as protobufMinimal from 'protobufjs/minimal';
                                ~~~~

node_modules/google-gax/build/src/fallback.d.ts:119:34 - error TS1005: ';' expected.

119 export * as protobufMinimal from 'protobufjs/minimal';
                                     ~~~~~~~~~~~~~~~~~~~~

node_modules/google-gax/build/src/index.d.ts:47:10 - error TS1005: 'from' expected.

47 export * as protobufMinimal from 'protobufjs/minimal';
            ~~

node_modules/google-gax/build/src/index.d.ts:47:13 - error TS1005: ';' expected.

47 export * as protobufMinimal from 'protobufjs/minimal';
               ~~~~~~~~~~~~~~~

node_modules/google-gax/build/src/index.d.ts:47:29 - error TS1005: ';' expected.

47 export * as protobufMinimal from 'protobufjs/minimal';
                               ~~~~

node_modules/google-gax/build/src/index.d.ts:47:34 - error TS1005: ';' expected.

47 export * as protobufMinimal from 'protobufjs/minimal';
                                    ~~~~~~~~~~~~~~~~~~~~

Found 8 errors.
```

This is the tsconfig file I used:
```json
{
    "compilerOptions": {
      "target": "ES2018",                      
      "module": "commonjs",
      "strict": true,                           
      "types": ["node"],                              
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true, 
      "skipDefaultLibCheck": true
    },
}
```

#### Environment details

  - OS: MacOS 10.14.6
  - Node.js version: v12.14.0
  - npm version: 1.22.4 (Using Yarn)
  - `@google-cloud/datastore` version: 6.2.0
  - Typescript: 3.7.4

#### Steps to reproduce

  1. Run tsc --project ./tsconfig.json

Perhaps I'm doing something wrong with the tsconfig file, but it is working on a previous version. So I'm a bit confused. Any suggestions? Thank you!

**Comment by bcoe** [comment]
@ps-rruiz are you able to compile when you use `typescript@3.9.7`?

What is keeping you pinned on `3.7.4`?

**Comment by ps-rruiz** [comment]
Oh my goodness. Yes I can compile from Typescript@4.0.5 and the latest version of datastore.
I apologize for this issue! 
I was going crazy trying to figure it out at that time, and I totally did not think of all my options.

Appreciate it @bcoe Thank you!

**Comment by bcoe** [comment]
@ps-rruiz no worries at all, some folks have had good reasons to stay pinned on an old version of TypeScript (_which was why I asked_).

We're trying to figure out the best way to handle TypeScript updates, so that we don't cause trouble for folks.

I'm going to go ahead and close this, since you're unblocked.
