### ISSUE TITLE
Saving an empty Buffer throws an error.

### ISSUE THREAD

**Issue by vicb** [googleapis/nodejs-datastore#755]
#### Environment details

  - OS: MacOs
  - Node.js version: v14.4.0
  - npm version: 6.14.8
  - `@google-cloud/datastore` version: 6.3.0

#### Steps to reproduce

Execute the following code:

```typescript
async function saveBlob() {
  const key = datastore.key(['TEST']);
  
  await datastore.save({
    key: key,
    data: {
      name: 'test',
      blob: Buffer.from([])
    },
  });
}
```

It will trigger an error: `Error: 3 INVALID_ARGUMENT: The value "blob" does not contain a value.`

I expect to be able to save an empty Buffer without error.

If you change the blob value to `Buffer.from([1, 2, 3])` the error disappears.

My use case is that I have a protocol buffer composed of repeated fields only:

```proto
message LiveTrack {
  optional int64 id = 1 [jstype = JS_NUMBER];
  optional string name = 2;   
  repeated float lat = 3;
  repeated float lon = 4;
  repeated int32 alt = 5;
  repeated int32 time_sec = 6;
  repeated uint32 flags = 7;
  map<uint32, LiveExtra> extra = 8;
}
```

It could happen that all repeated fields (including the map) are empty. Because the optional field are not populated, the proto would serialize to an empty `Buffer`.

**Workaround**

The workaround would be to set the value to `null` when the Buffer size is 0.
This requires extra code both while saving (to replace the `Buffer` with `null`) and while loading (to replace `null` with the default message). 

**Other**

The wording of the message could be improved: `The value "blob" does not contain a value.`, i.e. use field or key instead of the first "value".

**Comment by vicb** [comment]
I have update `encodeValue` to read like:

```typescript
        if (value instanceof Buffer) {
            valueProto.blobValue = value.length == 0 ? '' : buffer;
            return valueProto;
        }
```

And it fixes the issue:
- The column is save as a Blob without vale (verified in the Cloud Console),
- Reading the column returns an empty buffer.

I suspect that the issue might originate in the library used to encode the protocol buffer ?

Anyway this code looks like a fix.

What do you think ?

**Comment by vicb** [comment]
I have done some digging into this bug:

/Users/berchet/Code/datastore/node_modules/@grpc/proto-loader/build/src/index.js

Calling `datastore.save(...)` ends up @grpc/proto-loader [`createSerializer`](https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/index.ts#L167-L172)

```typescript
function createSerializer(cls: Protobuf.Type): Serialize<object> {
  return function serialize(arg: object): Buffer {
    const message = cls.fromObject(arg);
    return cls.encode(message).finish() as Buffer;
  };
}
```

The problems seems to be in `const message = cls.fromObject(arg);`

The `arg` is:
```
mode:'NON_TRANSACTIONAL'
mutations:(1) [
  0: {
    upsert:{
      key:{path: Array(1)},
      properties:{
        name: {stringValue: 'test-null'},
        track: {blobValue: Buffer(0), excludeFromIndexes: true}
      }
    }
]
``` 

But the message has lost the value:

```
upsert: Entity {
  key:Key {path: Array(1)}
  properties: {
    name:Value {stringValue: 'test-null'}
    track:Value {excludeFromIndexes: true}
  }
}
```

The track should have `blobValue: ''`

**Comment by vicb** [comment]
It seems like this might be related to https://github.com/protobufjs/protobuf.js/pull/1500 ?

**Comment by vicb** [comment]
Patching protobufjs/protobuf.js#1500 did resolve the issue.

I'll try to move that PR forward and then propagate the fix through the dependencies.

**Comment by crwilcox** [comment]
What work remains to close this issue?

**Comment by vicb** [comment]
See https://github.com/protobufjs/protobuf.js/pull/1514#pullrequestreview-545366600, the proper fix in protobuf.js should be in v7 

The current nodejs-datastore code uses [a workaround](https://github.com/googleapis/nodejs-datastore/pull/767/files#diff-943283b35b29d42b616883e0c704cd3a6a1b6e15872d7708c4f04f1caf330524R635) that could be removed once protobuf.js is fixed - that v7 is released and nodejs-datastore is updated to use this dep.



/cc @alexander-fenster

**Comment by crwilcox** [comment]
Update v7.0 of protobuf is staged but not relased.

https://github.com/protobufjs/protobuf.js/pull/1519

**Comment by meredithslota** [comment]
https://github.com/protobufjs/protobuf.js/releases shows releases for 7.x+ — checking to see if we've picked these up yet.

**Comment by meredithslota** [comment]
The current minimum version of `google-gax` required is 3.3.0, and it looks like `protobufjs` v7 was required in v3.1.4, so we should be good to go to unwind this workaround. I've removed the "external" label accordingly.

**Comment by danieljbruce** [comment]
Seems to run ok without workaround. Will create a PR and a test.

**Comment by danieljbruce** [comment]
https://github.com/googleapis/nodejs-bigtable

**Comment by danieljbruce** [comment]
https://github.com/googleapis/nodejs-datastore/pull/1072
