### ISSUE TITLE
transaction Error: entity is too big

### ISSUE THREAD

**Issue by adielmil** [googleapis/nodejs-datastore#77]
Hi, 
I'm running Node JS application on Google app engine Flexible Environment.
one of my entities has an array property and I'm saving it without Indexes ( excludeFromIndexes: true)
when I'm trying to update one of the entity that contains an array of 300-400 items inside I got an error:
3 INVALID_ARGUMENT: entity is too big.
I checked the entity size and it less than 1MB.

I made the same change via Google cloud DataStore console and it worked.

#### Environment details

  - OS:Google app engine Flexible Environment
  - Node.js version: >=7.10.0
  - npm version: 
  - `@google-cloud/datastore` version: 1.4.0

#### Steps to reproduce

  1. create datastore entity with 2 properties a. status  (String)  b. changes (Array of objects) fill the array with 400 items.
  2. update the entity with status "done"

Thanks to helpers.

**Comment by stephenplusplus** [comment]
Thanks for reporting. Here is the code I'm using, which is working successfully. Could you modify it so that it will fail?

```js
var key = datastore.key('Kind')
var changes = []
var numChanges = 400

while (numChanges--) changes.push({ change: true })

var data = {
  status: 'not done',
  changes,
}

datastore.insert({key, data}, err => {
  if (err) throw err

  console.log('data inserted successfully')

  data.status = 'done'
  datastore.update({ key, data }, err => {
    if (err) throw err
    console.log('data updated successfully')
  })
})
```

**Comment by adielmil** [comment]
fail code:
` 
var key = datastore.key('Kind')
    var changes = []
    var numChanges = 400
    var innerChange =function (){
        var changes = [];
        var numChanges = 20;
        while (numChanges--) changes.push( {
            "factor": 1.0909750792760444,
            "suggested": 0.09541075007901159,
            "name": "google-youtube"

        })
        return changes;
    };
    while (numChanges--) changes.push( {
        "factor": 1.0909750792760444,
        "suggested": 0.09541075007901159,
        "name": "google-android",
        "innerChanges":innerChange()

    })
    var job = {
        a:3,
        status: 'not done',
        changes:changes,
    }
    let newEntity = [];
    //convert entity to new format that allow to add excludeFromIndexes field
    for(let i in Object.keys(job)) {
        let key = Object.keys(job)[i];
        if (key === 'changes') {
            newEntity.push({name: key, value: job[key], excludeFromIndexes: true});
        } else if (key === 'timestamp') {
            newEntity.push({name: key, value: new Date()});
        } else {
            newEntity.push({name: key, value: job[key]});
        }
    };

    const entity = {
        key: key,
        data: newEntity
    };
    datastore.save(entity, err => {
        if (err) throw err

        console.log('data inserted successfully');
        const transaction = datastore.transaction();

        return transaction.run()
            .then(() => Promise.all([transaction.get(key)]))
            .then(async (results) => {
                const accounts = results
                    .map((result) => result[0]);
                console.log("update status");
                accounts[0].status= 'done';
                transaction.save([
                    {
                        key: key,
                        data: accounts[0]
                    }
                ]);
                return transaction.commit();
            })
            .catch((error) => {
                console.log("rollback transaction :" + error);
                transaction.rollback()
            });

    }); 
`
the main changes are: 1. use transaction 2. put an array inside the array.

**Comment by stephenplusplus** [comment]
Thanks, I ran that and received this error:

> Error: Too many indexed properties for entity: app: "s~nth-circlet-705",path <  Element {    type: "Kind",    id: 0x14341b3c000000  }>

I believe this is a limitation of the API, and not one set in our software. @alexander-fenster what do you think?

**Comment by adielmil** [comment]
when I ran your update code on the real entity I got:

> Error: 3 INVALID_ARGUMENT: entity is too big
    at new createStatusError (C:\dev-git\caw\node_modules\google-gax\node_modules\grpc\src\client.js:64:15)
    at C:\dev-git\caw\node_modules\google-gax\node_modules\grpc\src\client.js:583:15

**Comment by callmehiphop** [comment]
Hasn't been any activity here in a long time. @adielmil I'm going to close this out, but if you are still seeing this error let us know and we can continue to investigate.
