### ISSUE TITLE
Misconfiguration of apiEndpoint, servicePath or port causes hang on query

### ISSUE THREAD

**Issue by kevinohara80** [googleapis/nodejs-datastore#79]
#### Actual

Currently, when you execute a query with an invalid `apiEndpoint`, `servicePath` or `port`, the query executes but does not call the callback or reject a promise. It simply hangs with no error logging. This causes blocking in application code as the guarantee of a callback and/or promise is broken.

#### Expected

Misconfigured clients should error. When a Datastore client is misconfigured, queries should error appropriately by returning an error in the callback and/or rejecting the promise.

#### Environment details

  - OS: MacOS
  - Node.js version: 8.9.1
  - npm version: 5.8.1
  - `@google-cloud/datastore` version: 1.4.0

#### Steps to reproduce

  1. Configure a Datastore client as shown below
  2. Attempt to make a query
  3. Wait for callback and/or promise. Neither callbacks nor promises are resolved.

#### Example code

Datastore client configuration

```js
const datastore = new Datastore({
  servicePath: 'datastore.googleapis.com',
  port: 324 // invalid port
});
```

Or...

```js
const datastore = new Datastore({
  servicePath: 'zzzzzdatastore.googleapis.com' // invalid servicePath
});
```

Then try executing a query...

```js
const query = datastore.createQuery(NAMESPACE, KIND);

datastore.runQuery(query, function (err, records) {
  if (err) return reject(err);
  return resolve(records);
});
```

Or...

```js
const query = datastore.createQuery(NAMESPACE, KIND);

datastore.runQuery(query)
  .then(() => console.log('ok'))
  .catch(err => console.error(err))
```

**Comment by kevinohara80** [comment]
Even configuring your client like this hangs

```js
const datastore = new Datastore({
  keyFilename: gcpSecretPath,
  apiEndpoint: "https://datastore.googleapis.com"
});
```

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/gax-nodejs/issues/208.
