### ISSUE TITLE
Unable to filter property with null value

### ISSUE THREAD

**Issue by mlev** [googleapis/nodejs-datastore#958]
#### Environment details

  - OS: MacOS
  - Node.js version: 16.15.0
  - npm version: 8.5.5
  - `@google-cloud/datastore` version: 7.0.0

#### Steps to reproduce

Not sure if I'm missing something but currently any attempt to query by a value that might be null will result in TS error `Type 'null' is not assignable to type '{}'.`
e.g.
```
  const queryByStatus = (status: string | null) => {
    // Without operator
    const query1 = datastore.createQuery(kind).filter("status", status);
    // With operator
    const query2 = datastore.createQuery(kind).filter("status", "=", status);
  };
```

This is because the typings for `Query.filter` do not allow passing a null value:

```
filter(property: string, value: {}): Query;
filter(property: string, operator: Operator, value: {}): Query;
```

Note the workaround is to use the non-null operator `!` on the value but this isn't ideal.

**Comment by danieljbruce** [comment]
I tried this code and it works:

```
// Imports the Google Cloud client library
const {Datastore} = require('@google-cloud/datastore');

// Creates a client
const datastore = new Datastore();
const kind = 'Todo';

const queryByStatus = (status) => {
  // Without operator
  const query1 = datastore.createQuery(kind).filter("status", status);
  // With operator
  const query2 = datastore.createQuery(kind).filter("status", "=", status);
};
queryByStatus('complete');
queryByStatus(null);
```

I think this case is handled here now:

https://github.com/googleapis/nodejs-datastore/blob/release-v6.7.0/src/query.ts#L199

**Comment by danieljbruce** [comment]
We need to investigate if allowing `null` in place of `value` has unintended side effects. If it doesn't then I don't see a problem with implementing the change you suggested.

**Comment by danieljbruce** [comment]
It looks like when null is provided that we have custom code to support it so that it says the following:

`{"nullValue": 0}`

**Comment by danieljbruce** [comment]
We should just check other code paths to ensure this will be ok.

**Comment by danieljbruce** [comment]
Just did a search on `.filters` across this codebase and this seems fine. I think we can add this change.
