### ISSUE TITLE
Please support != (not equal), IN, NOT IN filters

### ISSUE THREAD

**Issue by Leejjon** [googleapis/nodejs-datastore#966]
Please implement the "special query types" that are supported in the Java & Python clients but not in Node.js as described here:
https://cloud.google.com/datastore/docs/concepts/queries#special_query_types

I used to have a Java backend on Google App Engine. Since my frontend was React.js with TypeScript, I switched to a Node.js TypeScript backend (to be able to have shared request and response objects on the frontend and backend). I recently have more of a need to query with an IN filter and noticed that I can't use this.

I have a script that stores football matches from over 10+ competitions in my datastore. My "getUpcoming10Matches" query needs to display the 10 upcoming matches from the competitions that a user selects. OR clauses are not possible as far as I know.
```
let query = datastore.createQuery('match')
     .order('startTimestamp', {descending: false})
     .filter('startTimestamp', '>', currentTimestamp.toJSON())
     .filter('competitionId', "2003")
     /* OR */
     .filter('competitionId', "2021")
     .limit(10);
```

I would like to do something like:
```
let query = datastore.createQuery('match')
    .order('startTimestamp', {descending: false})
    .filter('startTimestamp', '>', currentTimestamp.toJSON())
    .filter('competitionId', 'IN',  ["2003", "2021"])
    .limit(10);
```

My alternatives currently are:
1 Do two or more queries and merge the results from both and take the first 10 based on the start timestamp
2 Creating a Java or Python web service only for the specific query with the IN filter I need
3 Migrating my datastore to a native firestore (requires creating a new app engine project and migrating everything)

I'm probably going for option 1 until this is resolved.

**Comment by ip3ly5** [comment]
Also would appreciate this feature

**Comment by Leejjon** [comment]
When using the 'IN' operator like this:

```
let query = datastore.createQuery('match')
            .order('competitionId', {descending: false})
            .filter('competitionId', 'IN', ["2000", "2003", "2021"])
            .limit(10);
        const result = await datastore.runQuery(query);
```

I'm getting `3 INVALID_ARGUMENT: Filter has 3 properties, expected 1`.

I'd really like to see a working example.

**Comment by vicb** [comment]
Seems like there are examples in the tests:

https://github.com/googleapis/nodejs-datastore/blob/0ecca862fd93fc668a3dd3f5c93c54724e43f055/system-test/datastore.ts#L764-L789

Also `value: {}` would accept an array, see [this example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCm0YF4YAoCGAnA5gLhgG8BfAShQD4YwBXAGzoG4AoZhaNAbQEYAaGAEz8AzAF1SLIA)

**Comment by Leejjon** [comment]
Good news, my code works in the actual Google Datastore on the cloud.

Locally I test with the google-datastore emulator and there it only works if I query in an array with only one value:

```
let query = datastore.createQuery('match')
            .order('startTimestamp', {descending: false})
            .filter('startTimestamp', '>', currentTimestamp.toJSON())
            .filter('competitionId', 'IN', ["2003"])
            .limit(10);
const result: RunQueryResponse = await datastore.runQuery(query);
```

If I add two competitionId's in the array like:
```
let query = datastore.createQuery('match')
            .order('startTimestamp', {descending: false})
            .filter('startTimestamp', '>', currentTimestamp.toJSON())
            .filter('competitionId', 'IN', ["2003", "2021"])
            .limit(10);
const result: RunQueryResponse = await datastore.runQuery(query);
```
It still gives me: `3 INVALID_ARGUMENT: Filter has 2 properties, expected 1`

Could it be that my emulator is outdated or doesn't have this implemented properly?

I'm on Ubuntu and installed gcloud and the cloud-datastore-simulator using `apt-get install google-cloud-sdk-datastore-emulator`

If I try to update it it says: `google-cloud-sdk-datastore-emulator is already the newest version (412.0.0-0).`

The gcloud --version command says:
```
gcloud --version
Google Cloud SDK 412.0.0
alpha 2022.12.09
beta 2022.12.09
bq 2.0.83
bundled-python3-unix 3.9.12
cloud-datastore-emulator 2.3.0
core 2022.12.09
gcloud-crc32c 1.0.0
gsutil 5.17
```

**Comment by Leejjon** [comment]
In the docs of the emulator it still mentions it does not support IN queries under known issues:
https://cloud.google.com/datastore/docs/tools/datastore-emulator
